// This file is auto-generated by keycloakify. Do not edit it manually.
// Hash: d2eed76e05cc5e0b76816c67e39d45219837e15d249e9e35ad89af1bdd9b034a

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import type { ApplicationRef, ComponentRef, EnvironmentProviders, Type } from '@angular/core';

export type ThemeName = 'sic-keycloak-theme';

export const themeNames: ThemeName[] = ['sic-keycloak-theme'];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext = import('./login/KcContext').KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}

export async function bootstrapKcApplication(params: {
  kcContext: KcContext;
  bootstrapApplication: (params: {
    KcRootComponent: Type<unknown>;
    kcProvider: EnvironmentProviders;
  }) => Promise<ApplicationRef>;
}): Promise<ApplicationRef> {
  const { kcContext, bootstrapApplication } = params;
  let appRef: ApplicationRef;

  switch (kcContext.themeType) {
    case 'login':
      {
        const [
          { provideKeycloakifyAngular },
          { getI18n },
          {
            PageComponent,
            TemplateComponent,
            doUseDefaultCss,
            classes,
            UserProfileFormFieldsComponent,
            doMakeUserConfirmPassword,
          },
        ] = await Promise.all([
          import('@keycloakify/angular/login/providers/keycloakify-angular'),
          import('./login/i18n'),
          import('./login/KcPage').then(({ getKcPage }) => getKcPage(kcContext.pageId)),
        ] as const);

        appRef = await bootstrapApplication({
          KcRootComponent: TemplateComponent,
          kcProvider: provideKeycloakifyAngular({
            kcContext,
            classes,
            getI18n,
            doUseDefaultCss,
            doMakeUserConfirmPassword,
          }),
        });

        appRef.components.forEach((componentRef) => {
          // page must be defined first
          if ('page' in componentRef.instance) {
            componentRef.setInput('page', PageComponent);
          }
          if ('userProfileFormFields' in componentRef.instance) {
            componentRef.setInput('userProfileFormFields', UserProfileFormFieldsComponent);
          }
        });
      }
      break;
    default:
      throw new Error('wrong themeType');
  }

  return appRef;
}
