spring.datasource.url=jdbc:postgresql://localhost:54320/sic_db
spring.datasource.username=sic-app
spring.datasource.password=SicApp2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect