server:
  port: 5265

spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/sic_app
    username: sic-app
    password: SicApp2026
    driver-class-name: org.postgresql.Driver
    devtools:
      restart:
        enabled: true
        additional-paths: src/main/java, src/main/resources

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
    open-in-view: false

  web:
    cors:
      allowed-origins:
        - http://localhost:4200

  mail:
    host: smtp.gmail.com
    port: 587
    username: phurinsukman3@gmail.com
    password: qeivnricakfexxzh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  keycloak:
    realm: sic-project
    auth-server-url: http://localhost:8080
    ssl-required: none
    resource: sic-app
    verify-token-audience: false
    credentials:
      secret: ""
    confidential-port: 0

  # แก้ไขส่วนนี้ - ย้ายออกมาจากใต้ keycloak
  storage:
    s3:
      bucket: public-files
      region: ap-southeast-1
      access-key: seaweedfs
      secret-key: seaweedfs-secret

storage:
  service-url: http://localhost:8888
  access-key: seaweedfs
  secret-key: seaweedfs-secret
  image-bucket: public-files
  video-bucket: public-files
  document-bucket: documents

logging:
  pattern:
    console: "%msg%n"
  level:
    root: ERROR
    com.softinter.sicapi: DEBUG
    org.springframework.mail: DEBUG 
    com.softinter.sicapi.service.impl: DEBUG

spring.main.banner-mode: off