import { Injectable, inject, PLATFORM_ID } from '@angular/core';
import { DOCUMENT, isPlatformBrowser } from '@angular/common';
import { firstValueFrom, Observable } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';

export type AppLanguage = 'th' | 'en';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly document = inject(DOCUMENT);
  private readonly platformId = inject(PLATFORM_ID);
  private readonly translate = inject(TranslateService);
  private readonly storageKey = 'app-lang';

  constructor() {
    this.translate.onLangChange.subscribe(({ lang }) => {
      this.updateHtmlLang(lang as AppLanguage);
    });
  }

  private readonly defaultTranslations: Record<'th' | 'en', Record<string, string>> = {
    th: {
      COMMON_UNSAVED_CHANGES_TITLE: 'มีการเปลี่ยนแปลงที่ยังไม่บันทึก',
      COMMON_UNSAVED_CHANGES_MSG: 'คุณมีการเปลี่ยนแปลงที่ยังไม่บันทึก ต้องการออกจากหน้านี้หรือไม่?',
      DASHBOARD_CHIP_ACTIVE_PROJECTS: 'โครงการดำเนินงาน',
      DASHBOARD_CHIP_PENDING_APPROVALS: 'รออนุมัติ',
      DASHBOARD_CHIP_OPEN_BUGS: 'บั๊กค้าง',
      DASHBOARD_CHIP_EXPIRING_CONTRACTS: 'สัญญาใกล้หมดอายุ',
      CONTEXT_SWITCHER_TITLE: 'ตัวกรองและสลับโปรเจกต์',
      CONTEXT_SWITCHER_POPOVER_TITLE: 'ค้นหา & สลับโปรเจกต์',
      CONTEXT_SWITCHER_POPOVER_SUBTITLE: 'คัดกรองและเลือกโปรเจกต์การทำงาน',
      CONTEXT_SWITCHER_SELECT_PROMPT: 'เลือกโปรเจกต์ / ตัวกรอง...',
      CONTEXT_SWITCHER_CUSTOMER_SELECTED: 'เลือกลูกค้าแล้ว (ยังไม่เลือกโปรเจกต์)',
      CONTEXT_SWITCHER_SELECTED_PROJECT: 'โปรเจกต์ที่เลือก',
      CONTEXT_SWITCHER_PROJECTS_SELECTED: 'โปรเจกต์ที่เลือก',
      CONTEXT_SWITCHER_SEARCH_PLACEHOLDER: 'ค้นหาชื่อโปรเจกต์, รหัสโปรเจกต์...',
      CONTEXT_SWITCHER_CUSTOMER_LABEL: 'ลูกค้า',
      CONTEXT_SWITCHER_CUSTOMER_SEARCH_PLACEHOLDER: 'พิมพ์ค้นหาลูกค้า...',
      CONTEXT_SWITCHER_CUSTOMER_NOT_FOUND: 'ไม่พบรายชื่อลูกค้า',
      CONTEXT_SWITCHER_ALL_CUSTOMERS: 'ทุกลูกค้า (ทั้งหมด)',
      CONTEXT_SWITCHER_STATUS_LABEL: 'สถานะงาน',
      CONTEXT_SWITCHER_PRIORITY_LABEL: 'ระดับความสำคัญ',
      CONTEXT_SWITCHER_MATCHING_PROJECTS: 'โปรเจกต์ที่ตรงเงื่อนไข',
      CONTEXT_SWITCHER_LOADING_PROJECTS: 'กำลังโหลดรายการโปรเจกต์...',
      CONTEXT_SWITCHER_NO_MATCHING_PROJECTS: 'ไม่พบโปรเจกต์ตามเงื่อนไขตัวกรอง',
      CONTEXT_SWITCHER_CURRENT: 'ปัจจุบัน',
      CONTEXT_SWITCHER_SWITCH: 'สลับ',
      CONTEXT_SWITCHER_RESET_FILTERS: 'ล้างตัวกรอง',
      CONTEXT_SWITCHER_CLEAR_CONTEXT: 'ล้างบริบทปัจจุบัน',
      CONTEXT_SWITCHER_CLOSE: 'ปิด',
      CONTEXT_SWITCHER_SELECT_ALL: 'เลือกทั้งหมด',
      CONTEXT_SWITCHER_UNSELECT_ALL: 'ยกเลิกทั้งหมด',
      STATUS_ALL: 'ทั้งหมด',
      STATUS_PLANNING: 'วางแผน',
      STATUS_DEVELOPMENT: 'กำลังพัฒนา',
      STATUS_UAT: 'ทดสอบ',
      STATUS_BUG_FIXING: 'แก้ไขบั๊ก',
      STATUS_DELIVERED: 'ส่งมอบแล้ว',
      STATUS_CLOSED: 'ปิดงาน',
      PRIORITY_ALL: 'ทั้งหมด',
      PRIORITY_CRITICAL: 'ด่วนมาก',
      PRIORITY_HIGH: 'สูง',
      PRIORITY_MEDIUM: 'ปานกลาง',
      PRIORITY_LOW: 'ต่ำ',
      PRIORITY_NORMAL: 'ทั่วไป',
      PROJECT_HEALTH_WIDGET_TITLE: 'สุขภาพโครงการ',
      PROJECT_HEALTH_STATUS_GOOD: 'สุขภาพดี',
      PROJECT_HEALTH_STATUS_WARNING: 'เฝ้าระวัง',
      PROJECT_HEALTH_STATUS_CRITICAL: 'วิกฤต',
      PROJECT_HEALTH_TOTAL_SCORE: 'คะแนนสุขภาพรวม',
      PROJECT_HEALTH_FACTOR_TASKS: 'ความคืบหน้างาน',
      PROJECT_HEALTH_FACTOR_MANDAY: 'การใช้ Manday (จากงบทั้งหมด)',
      PROJECT_HEALTH_FACTOR_QUALITY: 'คุณภาพ & การแก้ไข Bug',
      PROJECT_HEALTH_FACTOR_PHASE: 'ความคืบหน้า Phase',
      PROJECT_HEALTH_FACTOR_TIMELINE: 'สถานะและกำหนดการ',
      PROJECT_HEALTH_DETAIL_NO_TASKS: 'ไม่มีงาน (0/0)',
      PROJECT_HEALTH_DETAIL_TASKS_PROGRESS: 'งานเสร็จ {{completed}}/{{total}} งาน ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_MANDAY_USAGE: '{{used}} / {{budget}} Manday ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_NO_BUGS: 'สมบูรณ์ ไม่มี Bug ในระบบ (0/0)',
      PROJECT_HEALTH_DETAIL_BUGS_PROGRESS: 'แก้ไขแล้ว {{closed}}/{{total}} Bug ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_NO_PHASES: 'ไม่มี Phase (0/0)',
      PROJECT_HEALTH_DETAIL_PHASES_PROGRESS: '{{completed}}/{{total}} Phase ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_ON_SCHEDULE: 'ตามแผนงาน',
      PROJECT_HEALTH_DETAIL_DELAYED: 'ล่าช้ากว่ากำหนด',
      PROJECT_HEALTH_DETAIL_COMPLETED: 'เสร็จสิ้นตามเป้าหมาย',
      PROJECT_HEALTH_DETAIL_OVERDUE: 'เกินกำหนดส่งมอบ',
      PORTFOLIO_GANTT_TITLE: 'ผังระยะเวลาโครงการองค์กร (Enterprise Portfolio Roadmap)',
      PORTFOLIO_GANTT_SUBTITLE: 'แสดงระยะเวลาและสถานะดำเนินงานทุกโครงการ แยกตามลูกค้ารายองค์กร',
      PORTFOLIO_GANTT_TOTAL_CUSTOMERS: 'ลูกค้าทั้งหมด',
      PORTFOLIO_GANTT_TOTAL_PROJECTS: 'โครงการทั้งหมด',
      PORTFOLIO_GANTT_ACTIVE: 'กำลังดำเนินงาน',
      PORTFOLIO_GANTT_DELAYED: 'ล่าช้ากว่าแผน',
      PORTFOLIO_GANTT_COMPLETED: 'เสร็จสิ้นแล้ว',
      PORTFOLIO_GANTT_EXPAND_ALL: 'ขยายทั้งหมด',
      PORTFOLIO_GANTT_COLLAPSE_ALL: 'พับทั้งหมด',
      PORTFOLIO_GANTT_VIEW_MONTH: 'รายเดือน',
      PORTFOLIO_GANTT_VIEW_WEEK: 'รายสัปดาห์',
      PORTFOLIO_GANTT_VIEW_DAY: 'รายวัน',
      PORTFOLIO_GANTT_SEARCH_PLACEHOLDER: 'ค้นหาโครงการ, ลูกค้า, หรือ PM...',
      PORTFOLIO_GANTT_CUSTOMER_ALL: 'ทุกลูกค้า (All Customers)',
      PORTFOLIO_GANTT_STATUS_ALL: 'ทุกสถานะ',
      PORTFOLIO_GANTT_LEGEND_ON_TRACK: 'ตามแผนงาน',
      PORTFOLIO_GANTT_LEGEND_DELAYED: 'ล่าช้ากว่ากำหนด',
      PORTFOLIO_GANTT_LEGEND_PLANNING: 'กำลังวางแผน',
      PORTFOLIO_GANTT_LEGEND_COMPLETED: 'เสร็จสิ้น',
      PORTFOLIO_GANTT_NO_DATA: 'ไม่พบข้อมูลโครงการตามเงื่อนไขตัวกรอง',
      PORTFOLIO_GANTT_VIEW_DETAILS: 'ดูรายละเอียดโครงการ',
      PORTFOLIO_GANTT_VIEW_BOARD: 'เปิด Task Board & Phase Gantt',
      PORTFOLIO_GANTT_PROJECTS_COUNT: '{{count}} โครงการ',
      PMDT17A_CONTRACT_LABEL: 'สัญญา',
      PMDT17A_SELECT_CONTRACT_PLACEHOLDER: 'เลือกสัญญา',
      PMDT16A_LBL_DELIVERY: 'Delivery',
      PMDT16A_PH_DELIVERY: 'เลือก Delivery',
      PMDT14_GATE_CHECK_TITLE: 'การตรวจสอบความพร้อมส่งมอบ',
      PMDT14_CHECK_GATE_BTN: 'ตรวจสอบใหม่',
      PMDT14_CHECKING: 'กำลังตรวจสอบ...',
      PMDT14_PASSED_MARK: 'ผ่าน',
      PMDT14_FAILED_MARK: 'ต้องดำเนินการ',
      PMDT14_VIEW_DATA: 'ดูรายละเอียด',
      PMDT14_GO_MANAGE_PENDING: 'ไปจัดการรายการค้าง',
      PMDT14_GATE_STATUS_LABEL: 'สถานะ Gate Check:',
      PMDT14_STATUS_READY: 'พร้อมส่งมอบ',
      PMDT14_HAS_CONDITIONS: 'ยังมีเงื่อนไขที่ต้องแก้ไข',
      PMDT14_PASSED_WORD: 'ผ่าน',
      PMDT14_OUT_OF_WORD: 'จากทั้งหมด',
      PMDT14_CHECKS_WORD: 'ข้อกำหนด',
      PMDT14_GATE_EMPTY_HINT: 'กรุณาเลือกสัญญาหรือโครงการเพื่อตรวจสอบความพร้อมส่งมอบ',
      PMDT14_CLICK_TO_MANAGE_TIP: 'คลิกเพื่อไปจัดการข้อมูลในโมดูลนี้',
      PMDT10_PAGE_DESC: 'ติดตามสถานะงานจริงและ Traceability',
      PMDT10_TOTAL_LABEL: 'ทั้งหมด',
      PMDT10_UNIT_TASK: 'งาน',
      PMDT10_INPROGRESS_LABEL: 'กำลังทำ',
      PMDT10_BUG_LABEL: 'Bug ค้าง',
      PMDT10_BUG_DONE_LABEL: 'Bug เสร็จ',
      PMDT10_DONE_LABEL: 'เสร็จสิ้น',
      PMDT10_CREATE_TASK_BTN: 'สร้าง Task',
      PMDT10_NO_TASK_TITLE: 'ยังไม่มี Task ในระบบ',
      PMDT10_NO_TASK_DESC: 'เริ่มต้นด้วยการสร้าง Task เพื่อจัดการงานและติดตามความคืบหน้า',
      PMDT10_SELECT_PROJECT_MSG: 'ยังไม่มี Task ในระบบ',
      PMDT10_SELECT_PROJECT_HINT: 'เริ่มต้นด้วยการสร้าง Task เพื่อจัดการงานและติดตามความคืบหน้า',
      PMDT10_GO_PROJECT_LIST_BTN: 'สร้าง Task',
      PMDT10_SEARCH_PH: 'ค้นหาชื่อ Task, รหัสงาน...',
      PMDT10_SPEC_PH: 'ทุก Specification',
      PMDT10_WP_PH: 'ทุก Work Package',
      PMDT10_PRIORITY_PH: 'ทุกความสำคัญ',
      PMDT10_ASSIGNEE_PH: 'ทุกผู้รับผิดชอบ',
      PMDT10_CLEAR_FILTER_BTN: 'ล้างตัวกรอง',
      PMDT10_TABLE_VIEW_BTN: 'ตาราง',
      PMDT10_LOADING_TASK: 'กำลังโหลดข้อมูล Task...',
      PMDT10_DELETE_TASK_TITLE: 'ลบ Task',
      PMDT10_PRIO_CRITICAL: 'วิกฤต',
      PMDT10_PRIO_HIGH: 'สูง',
      PMDT10_PRIO_MEDIUM: 'ปานกลาง',
      PMDT10_PRIO_LOW: 'ต่ำ',
      PMDT10_PRIO_CRITICAL_PLAIN: 'วิกฤต',
      PMDT10_PRIO_HIGH_PLAIN: 'สูง',
      PMDT10_PRIO_MEDIUM_PLAIN: 'ปานกลาง',
      PMDT10_PRIO_LOW_PLAIN: 'ต่ำ',
      PMDT10_COL_TASK_CODE: 'รหัส Task',
      PMDT10_COL_TASK_NAME: 'ชื่องาน',
      PMDT10_COL_ASSIGNEE: 'ผู้รับผิดชอบ',
      PMDT10_COL_MANDAY: 'Manday (จริง / ประเมิน)',
      PMDT10_COL_STATUS: 'สถานะ',
      PMDT10_COL_PRIORITY: 'ความสำคัญ',
      PMDT10_COL_DUE_DATE: 'วันครบกำหนด',
      PMDT10_COL_ACTIONS: 'จัดการ',
      PMDT10_EDIT_TASK_TITLE: 'แก้ไข Task',
      PMDT10_NEW_TASK_TITLE: 'สร้าง Task',
      PMDT10_MODAL_DESC: 'กรอกรายละเอียดงานและผู้รับผิดชอบ',
      PMDT10_SPEC_TRACE_LABEL: 'Specification (Traceability)',
      PMDT10_SPEC_SELECT_PH: 'เลือก Specification...',
      PMDT10_SPEC_REQUIRED_MSG: 'กรุณาเลือก Specification',
      PMDT10_WP_LABEL: 'Work Package',
      PMDT10_WP_SELECT_PH: 'เลือก Work Package...',
      PMDT10_WP_REQUIRED_MSG: 'กรุณาเลือก Work Package',
      PMDT10_TASK_CODE_LABEL: 'รหัส Task',
      PMDT10_TASK_CODE_PH: 'เช่น TSK-001',
      PMDT10_TASK_CODE_REQUIRED_MSG: 'กรุณากรอกรหัส Task',
      PMDT10_TASK_NAME_LABEL: 'ชื่องาน',
      PMDT10_TASK_NAME_PH: 'เช่น พัฒนาระบบส่วนติดต่อผู้ใช้',
      PMDT10_TASK_NAME_REQUIRED_MSG: 'กรุณากรอกชื่องาน',
      PMDT10_TASK_DESC_LABEL: 'รายละเอียดงาน',
      PMDT10_TASK_DESC_PH: 'อธิบายรายละเอียดของงาน...',
      PMDT10_ASSIGNEE_FIELD_LABEL: 'ผู้รับผิดชอบหลัก',
      PMDT10_ASSIGNEE_FIELD_PH: 'เลือกผู้รับผิดชอบ...',
      PMDT10_START_DATE_LABEL: 'วันที่เริ่ม',
      PMDT10_START_DATE_PH: 'เลือกวันที่เริ่ม',
      PMDT10_START_TIME_LABEL: 'เวลาเริ่ม',
      PMDT10_END_DATE_LABEL: 'วันที่สิ้นสุด',
      PMDT10_END_DATE_PH: 'เลือกวันที่สิ้นสุด',
      PMDT10_END_TIME_LABEL: 'เวลาสิ้นสุด',
      PMDT10_TIME_PH: '09:00',
      PMDT10_ESTIMATE_MANDAY_LABEL: 'ประมาณการ Manday',
      PMDT10_ACTUAL_MANDAY_LABEL: 'Manday ที่ใช้จริง',
      PMDT10_PRIORITY_FIELD_LABEL: 'ระดับความสำคัญ',
      PMDT10_PRIORITY_SELECT_PH: 'เลือกระดับความสำคัญ',
      PMDT10_COLOR_TAG_LABEL: 'แท็กสี',
      PMDT10_CANCEL_BTN: 'ยกเลิก',
      PMDT10_SAVING_TEXT: 'กำลังบันทึก...',
      PMDT10_SAVE_EDIT_BTN: 'บันทึกการแก้ไข',
      PMDT10_CONFIRM_DELETE_TITLE: 'ยืนยันการลบ',
      PMDT10_CONFIRM_DELETE_MSG: 'คุณต้องการลบ Task นี้หรือไม่?',
      PMDT10_DELETE_SUCCESS_TITLE: 'ลบสำเร็จ',
      PMDT10_DELETE_SUCCESS_MSG: 'ลบ Task เรียบร้อยแล้ว',
      PMDT10_DELETE_ERROR_TITLE: 'เกิดข้อผิดพลาด',
      PMDT10_INCOMPLETE_DATA_TITLE: 'ข้อมูลไม่ครบถ้วน',
      PMDT10_INCOMPLETE_DATA_MSG: 'กรุณากรอกข้อมูลในช่องที่จำเป็น (*) ให้ครบถ้วน',
      PMDT10_SAVE_SUCCESS_TITLE_A: 'บันทึกสำเร็จ',
      PMDT10_CREATE_TASK_SUCCESS_MSG: 'สร้าง Task เรียบร้อยแล้ว',
      PMDT10_UPDATE_TASK_SUCCESS_MSG: 'บันทึกการแก้ไข Task เรียบร้อยแล้ว',
      PMDT10_SAVE_ERROR_TITLE_A: 'บันทึกไม่สำเร็จ',
      PMDT10_SAVE_TASK_ERROR_MSG: 'เกิดข้อผิดพลาดในการบันทึก Task',
      PMDT10_LOAD_FAIL_TITLE: 'โหลดข้อมูลไม่สำเร็จ',
      PMDT10_LOAD_TASKS_FAIL_MSG: 'ไม่สามารถโหลดข้อมูล Task ได้',
      PMDT10_LOAD_BUGS_FAIL_MSG: 'ไม่สามารถโหลดข้อมูล Bug ได้',
      PMDT10_NO_FILTER_RESULT_MSG: 'ไม่พบ Task ที่ตรงกับเงื่อนไขการค้นหา',
      PMDT09_PROJECT_LABEL: 'โครงการ',
      PMDT09_PROJECT_PLACEHOLDER: 'เลือกโครงการ',
      PMDT09_REVIEW_CODE_LABEL: 'รหัส Design Review',
      PMDT09_REVIEW_CODE_PLACEHOLDER: 'เช่น DR-001',
      PMDT09_TITLE_LABEL: 'หัวข้อการตรวจทาน',
      PMDT09_TITLE_PLACEHOLDER: 'ระบุหัวข้อการตรวจทาน',
      PMDT09_SEVERITY_FIELD_LABEL: 'ระดับความรุนแรง',
      PMDT09_SEV_SELECT_PH: 'เลือกระดับความรุนแรง',
      PMDT09_STATUS_LABEL: 'สถานะ',
      PMDT09_STATUS_SELECT_PH: 'เลือกสถานะ',
      PMDT09_DUE_DATE_LABEL: 'กำหนดเสร็จ',
      PMDT09_ASSIGNED_TO_LABEL: 'ผู้รับผิดชอบแก้ไข',
      PMDT09_ASSIGNED_TO_PH: 'เลือกผู้รับผิดชอบ...',
      PMDT09_APPROVAL_FLOW_LABEL: 'ขั้นตอนการอนุมัติ',
      PMDT09_APPROVAL_FLOW_PH: 'เลือกขั้นตอนการอนุมัติ...',
      PMDT09_DESC_LABEL: 'รายละเอียดการตรวจทาน',
      PMDT09_DESC_PLACEHOLDER: 'ระบุรายละเอียด ข้อคิดเห็น หรือจุดที่ต้องปรับปรุง...',
      PMDT09_FIGMA_URL_LABEL: 'Figma File / Prototype URL',
      PMDT09_FIGMA_URL_PH: 'https://www.figma.com/file/...',
      PMDT09_PAGE_TITLE: 'การตรวจทานการออกแบบ (Design Review)',
      PMDT09_PAGE_DESC: 'ศูนย์รวมการตรวจทานและอนุมัติแบบ UI/UX จาก Figma และ Prototype',
      PMDT09_CREATE_BTN: 'สร้าง Design Review',
      PMDT09_SEARCH_PLACEHOLDER: 'ค้นหารหัส, ชื่องาน, ผู้สร้าง...',
      PMDT09_STATUS_PLACEHOLDER: 'ทุกสถานะ',
      PMDT09_TYPE_PLACEHOLDER: 'ทุกประเภท',
      PMDT09_SEVERITY_PLACEHOLDER: 'ทุกระดับความรุนแรง',
      PMDT09_EMPTY_TITLE: 'ยังไม่มี Design Review ในระบบ',
      PMDT09_EMPTY_DESC: 'เริ่มต้นด้วยการสร้าง Design Review ใหม่ เพื่อตรวจสอบความถูกต้องของหน้าจอ',
      PMDT09_CANCEL_BTN: 'ยกเลิก',
      PMDT09_SAVE_BTN: 'บันทึก',
      PMDT09_SUBMIT_APPROVAL_BTN: 'ส่งขออนุมัติ',
      PMDT03_PAGE_TITLE: 'ศูนย์การอนุมัติ',
      PMDT03_SUBTITLE: 'จัดการสายการอนุมัติและรายการรออนุมัติ',
      PMDT03_MY_PENDING_TITLE: 'รอฉันอนุมัติ',
      PMDT03_OVERDUE_TITLE: 'รายการเกินกำหนด',
      PMDT03_ALL_STATUS_PLACEHOLDER: 'ทุกสถานะ',
      PMDT03_SELECT_PROJECT_PLACEHOLDER: 'เลือกโครงการ',
      PMDT03_COL_TYPE_CODE: 'ประเภท / รหัสเอกสาร',
      PMDT03_COL_ITEM: 'หัวข้อ / รายการ',
      PMDT03_COL_PROJECT: 'โครงการ',
      PMDT03_COL_REQUESTER: 'ผู้ยื่นคำขอ',
      PMDT03_COL_REQUESTED_DATE: 'วันที่ยื่นขอ',
      PMDT03_COL_STATUS: 'สถานะ',
      PMDT03_COL_ACTIONS: 'จัดการ',
      PMDT03_STATUS_PENDING: 'รอดำเนินการ',
      PMDT03_STATUS_APPROVED: 'อนุมัติแล้ว',
      PMDT03_STATUS_REJECTED: 'ปฏิเสธ',
      PMDT03_STATUS_NEED_REVISION_OPT: 'ต้องแก้ไข',
      PMDT03_STATUS_CANCELLED: 'ยกเลิก',
      PMDT03_PROJECT_CRM: 'ระบบจัดการลูกค้าสัมพันธ์ (CRM)',
      PMDT03_PROJECT_HR: 'ระบบบริหารงานบุคคล (HRMS)',
      PMDT03_ITEMS_SUFFIX: 'รายการ',
      PMDT03_ITEMS_UNIT: 'รายการ',
      PMDT03_NO_USER_TITLE: 'ไม่พบข้อมูลผู้ใช้',
      PMDT03_RELOGIN_MSG: 'กรุณาเข้าสู่ระบบใหม่',
      PMDT05_REQUIREMENT_LABEL: 'ความต้องการ',
      PMDT05_REQUIREMENT_PLACEHOLDER: 'เลือกความต้องการที่เกี่ยวข้อง (ไม่บังคับ)',
      PMDT05_REQ_SOURCE_LABEL: 'ความต้องการต้นทาง:',
      PMDT07_REQUIREMENT_LABEL: 'ความต้องการ',
      PMDT07_REQUIREMENT_PLACEHOLDER: 'เลือก Requirement',
      PMDT07_SPEC_CODE_LABEL: 'รหัส Specification',
      PMDT07_SPEC_CODE_PLACEHOLDER: 'เช่น SPEC-001',
      PMDT07_SPEC_TYPE_LABEL: 'ประเภท Specification',
      PMDT07_SPEC_TYPE_PLACEHOLDER: 'เลือกประเภท Specification',
      PMDT07_TITLE_LABEL: 'ชื่อเอกสาร Specification',
      PMDT07_TITLE_PLACEHOLDER: 'ระบุชื่อ Specification',
      PMDT07_PRIORITY_LABEL: 'ความสำคัญ',
      PMDT07_PRIORITY_PLACEHOLDER: 'เลือกระดับความสำคัญ',
      PMDT07_ASSIGNEE_LABEL: 'ผู้รับผิดชอบ',
      PMDT07_ASSIGNEE_PLACEHOLDER: 'เลือกผู้รับผิดชอบ',
      PMDT07_ESTIMATED_MANDAY_LABEL: 'Estimated Manday',
      PMDT07_ESTIMATED_MANDAY_PLACEHOLDER: 'ระบุ Manday',
      PMDT07_DESC_LABEL: 'รายละเอียด Specification',
      PMDT07_DESC_PLACEHOLDER: 'พิมพ์รายละเอียดที่นี่...',
      PMDT07_ATTACHMENTS_LABEL: 'เอกสารแนบ',
      PMDT07_ATTACHMENTS_HELPER: 'ลากไฟล์มาวาง หรือ คลิกเพื่ออัปโหลด',
      PMDT07_CREATE_SPEC_TITLE: 'สร้าง Specification',
      PMDT07_EDIT_SPEC_TITLE: 'แก้ไข Specification',
      PMDT07_VIEW_SPEC_TITLE: 'รายละเอียด Specification',
      PMDT07_CANCEL_BTN: 'ยกเลิก',
      PMDT07_SAVE_BTN: 'บันทึก',
      PMDT07_SUBMIT_BTN: 'ส่งขออนุมัติ',
      PMDT07_HEADER_TITLE: 'รายการ Specification',
      PMDT01_CREATE_PHASE_TITLE: 'สร้าง Phase',
      PMDT01_EDIT_PHASE_TITLE: 'แก้ไข Phase',
      PMDT01_EMPTY_TITLE: 'ยังไม่มี Phase ในโครงการนี้',
      PMDT01_EMPTY_HINT: 'เริ่มต้นด้วยการคลิกปุ่ม "+ เพิ่ม Phase" ด้านบนเพื่อวางแผนงานและไมล์สโตน',
      PMDT01_CUSTOMER_LABEL: 'ลูกค้า',
      PMDT01_CUSTOMER_PLACEHOLDER: 'ค้นหาและเลือกลูกค้า',
      PMDT01_PROJECT_LABEL: 'โครงการ',
      PMDT01_PROJECT_PLACEHOLDER: 'ค้นหาและเลือกโครงการ',
      PMDT02_CREATE_MS_TITLE_H: 'สร้าง Milestone',
      PMDT02_EDIT_MS_TITLE_H: 'แก้ไข Milestone',
      PMDT02_PHASE_LABEL: 'เฟส (Phase)',
      PMDT02_SELECT_PHASE_PLACEHOLDER: 'ค้นหาและเลือกเฟส',
      PMDT02_CREATE_WP_TITLE_H: 'สร้าง Work Package',
      PMDT02_EDIT_WP_TITLE_H: 'แก้ไข Work Package',
      PMDT02_MILESTONE_LABEL: 'ไมล์สโตน (Milestone)',
      PMDT02_SELECT_MILESTONE_PLACEHOLDER: 'ค้นหาและเลือกไมล์สโตน',
      PMDT02_CREATE_TASK_TITLE_H: 'สร้าง Task',
      PMDT02_EDIT_TASK_TITLE_H: 'แก้ไข Task',
      PMDT02_WORK_PACKAGE_LABEL: 'แพ็กเกจงาน (Work Package)',
      PMDT02_SELECT_WP_PLACEHOLDER: 'ค้นหาและเลือกแพ็กเกจงาน',
      PMDT06_CUSTOMER_LABEL: 'ลูกค้า',
      PMDT06_CUSTOMER_PLACEHOLDER: 'ค้นหาและเลือกลูกค้า',
      PMDT06_PROJECT_LABEL: 'โครงการ',
      PMDT06_UPSTREAM_CONTEXT_LABEL: 'ผลกระทบระดับโครงการและลูกค้า (Upstream Impact)',
      PMDT06_IMPACT_CUSTOMERS_LABEL: 'ลูกค้าที่ได้รับผลกระทบ',
      PMDT06_IMPACT_PROJECTS_LABEL: 'โครงการที่ได้รับผลกระทบ',
      PMDT06_IMPACT_REQUIREMENT: 'ความต้องการ (Requirement)',
      PMDT06_IMPACT_SPECIFICATION: 'ข้อกำหนด (Specification)',
      PMDT06_IMPACT_DIAGRAM: 'แผนภาพ (Diagram)',
      PMDT06_IMPACT_TASK: 'งาน (Task)',
      PMDT06_IMPACT_TESTCASE: 'ชุดทดสอบ (Test Case)',
      PMDT06_IMPACT_TESTPLAN: 'แผนทดสอบ (Test Plan)',
      PMDT06_IMPACT_BUG: 'ข้อผิดพลาด (Bug)',
      PMDT06_IMPACT_CONTRACT: 'สัญญาโครงการ',
      PMDT06_IMPACT_DESIGNREVIEW: 'ผลตรวจทานการออกแบบ',
      PMDT06_IMPACT_DELIVERY: 'การส่งมอบงาน',
      PMDT06_IMPACT_USERMANUAL: 'คู่มือการใช้งาน',
      PMDT06_IMPACT_INVOICE: 'ใบแจ้งหนี้/การชำระเงิน',
      PMDT06_IMPACT_MATICKET: 'แจ้งซ่อม MA',
      PMDT06_IMPACT_MARENEWAL: 'ต่ออายุ MA',
      PMDT12_SEARCH_PLACEHOLDER: 'ค้นหา Scenario, รหัสเคส, หัวข้อ, ผู้ทดสอบ...',
      PMDT12_FILTER_STATUS_PH: '📊 ทุกสถานะ Test Case',
      PMDT12_FILTER_PRIORITY_PH: '⚡ ทุกระดับความสำคัญ',
      PMDT12_FILTER_TASK_STATUS_PH: '🎯 ทุกสถานะ Task',
      PMDT12_SEVERITY_LABEL: 'ระดับความรุนแรง',
      PMDT12_SEVERITY_PH: 'เลือกระดับความรุนแรง',
      PMDT12_BUG_TITLE_LABEL: 'ชื่อ / หัวข้อ Bug',
      PMDT12_BUG_TITLE_PH: 'ระบุข้อผิดพลาดที่พบ...',
      PMDT12_ASSIGNED_TO_LABEL: 'ผู้รับผิดชอบแก้ไข',
      PMDT12_ASSIGNED_TO_PH: 'เลือกสมาชิกทีมผู้รับผิดชอบ',
      PMDT12_MANDAY_LABEL: 'ประมาณการ Manday',
      PMDT12B_TASK_TRACE_LABEL: 'Task',
      PMDT12B_TASK_TRACE_PLACEHOLDER: 'เลือก Task',
      PMDT12B_SCENARIO_CODE_LABEL: 'รหัส Test Scenario',
      PMDT12B_SCENARIO_CODE_PLACEHOLDER: 'เช่น SC-001, SC-LOGIN',
      PMDT12B_SCENARIO_NAME_LABEL: 'ชื่อ Test Scenario',
      PMDT12B_SCENARIO_NAME_PLACEHOLDER: 'เช่น การเข้าสู่ระบบ, การพิมพ์รายงาน...',
      PMDT12B_TEST_TYPE_LABEL: 'ประเภทการทดสอบ',
      PMDT12B_TEST_TYPE_PLACEHOLDER: 'เลือกประเภทการทดสอบ',
      PMDT12B_PRIORITY_LABEL: 'ความสำคัญ',
      PMDT12B_PRIORITY_PLACEHOLDER: 'เลือกระดับความสำคัญ',
      PMDT12B_DESCRIPTION_LABEL: 'คำอธิบาย / วัตถุประสงค์ของ Scenario',
      PMDT12B_DESCRIPTION_PLACEHOLDER: 'อธิบายขอบเขตและวัตถุประสงค์ในการทดสอบกลุ่มนี้...',
      PMDT12B_RICH_TEXT_HINT: 'รองรับการจัดรูปแบบข้อความ',
      PMDT12B_STATUS_ACTIVE_LABEL: 'เปิดใช้งาน',
    },
    en: {
      COMMON_UNSAVED_CHANGES_TITLE: 'Unsaved Changes',
      COMMON_UNSAVED_CHANGES_MSG: 'You have unsaved changes. Leave this page anyway?',
      DASHBOARD_CHIP_ACTIVE_PROJECTS: 'Active Projects',
      DASHBOARD_CHIP_PENDING_APPROVALS: 'Pending Approvals',
      DASHBOARD_CHIP_OPEN_BUGS: 'Open Bugs',
      DASHBOARD_CHIP_EXPIRING_CONTRACTS: 'Expiring Contracts',
      CONTEXT_SWITCHER_TITLE: 'Filter & Switch Project',
      CONTEXT_SWITCHER_POPOVER_TITLE: 'Find & Switch Project',
      CONTEXT_SWITCHER_POPOVER_SUBTITLE: 'Filter and select projects',
      CONTEXT_SWITCHER_SELECT_PROMPT: 'Select project / filter...',
      CONTEXT_SWITCHER_CUSTOMER_SELECTED: 'Customer selected (No project selected)',
      CONTEXT_SWITCHER_SELECTED_PROJECT: 'Selected Project',
      CONTEXT_SWITCHER_PROJECTS_SELECTED: 'projects selected',
      CONTEXT_SWITCHER_SEARCH_PLACEHOLDER: 'Search project name, code...',
      CONTEXT_SWITCHER_CUSTOMER_LABEL: 'Customer',
      CONTEXT_SWITCHER_CUSTOMER_SEARCH_PLACEHOLDER: 'Type to search customer...',
      CONTEXT_SWITCHER_CUSTOMER_NOT_FOUND: 'No customers found',
      CONTEXT_SWITCHER_ALL_CUSTOMERS: 'All Customers',
      CONTEXT_SWITCHER_STATUS_LABEL: 'Status',
      CONTEXT_SWITCHER_PRIORITY_LABEL: 'Priority',
      CONTEXT_SWITCHER_MATCHING_PROJECTS: 'Matching Projects',
      CONTEXT_SWITCHER_LOADING_PROJECTS: 'Loading projects...',
      CONTEXT_SWITCHER_NO_MATCHING_PROJECTS: 'No projects match the filter criteria',
      CONTEXT_SWITCHER_CURRENT: 'Current',
      CONTEXT_SWITCHER_SWITCH: 'Switch',
      CONTEXT_SWITCHER_RESET_FILTERS: 'Reset Filters',
      CONTEXT_SWITCHER_CLEAR_CONTEXT: 'Clear Current Context',
      CONTEXT_SWITCHER_CLOSE: 'Close',
      CONTEXT_SWITCHER_SELECT_ALL: 'Select All',
      CONTEXT_SWITCHER_UNSELECT_ALL: 'Deselect All',
      STATUS_ALL: 'All',
      STATUS_PLANNING: 'Planning',
      STATUS_DEVELOPMENT: 'Development',
      STATUS_UAT: 'UAT',
      STATUS_BUG_FIXING: 'Bug Fixing',
      STATUS_DELIVERED: 'Delivered',
      STATUS_CLOSED: 'Closed',
      PRIORITY_ALL: 'All',
      PRIORITY_CRITICAL: 'Critical',
      PRIORITY_HIGH: 'High',
      PRIORITY_MEDIUM: 'Medium',
      PRIORITY_LOW: 'Low',
      PRIORITY_NORMAL: 'Normal',
      PROJECT_HEALTH_WIDGET_TITLE: 'Project Health',
      PROJECT_HEALTH_STATUS_GOOD: 'Good Health',
      PROJECT_HEALTH_STATUS_WARNING: 'Needs Attention',
      PROJECT_HEALTH_STATUS_CRITICAL: 'Critical',
      PROJECT_HEALTH_TOTAL_SCORE: 'Overall Health Score',
      PROJECT_HEALTH_FACTOR_TASKS: 'Task Progress',
      PROJECT_HEALTH_FACTOR_MANDAY: 'Manday Usage (vs Budget)',
      PROJECT_HEALTH_FACTOR_QUALITY: 'Quality & Bug Fixing',
      PROJECT_HEALTH_FACTOR_PHASE: 'Phase Progress',
      PROJECT_HEALTH_FACTOR_TIMELINE: 'Timeline & Schedule Status',
      PROJECT_HEALTH_DETAIL_NO_TASKS: 'No tasks (0/0)',
      PROJECT_HEALTH_DETAIL_TASKS_PROGRESS: 'Tasks completed {{completed}}/{{total}} ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_MANDAY_USAGE: '{{used}} / {{budget}} Manday ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_NO_BUGS: 'Clean, no open bugs (0/0)',
      PROJECT_HEALTH_DETAIL_BUGS_PROGRESS: 'Fixed {{closed}}/{{total}} bugs ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_NO_PHASES: 'No phases (0/0)',
      PROJECT_HEALTH_DETAIL_PHASES_PROGRESS: '{{completed}}/{{total}} Phases ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_ON_SCHEDULE: 'On Schedule',
      PROJECT_HEALTH_DETAIL_DELAYED: 'Behind Schedule',
      PROJECT_HEALTH_DETAIL_COMPLETED: 'Completed as Planned',
      PROJECT_HEALTH_DETAIL_OVERDUE: 'Overdue / Delivery Passed',
      PORTFOLIO_GANTT_TITLE: 'Enterprise Portfolio Roadmap (Gantt Chart)',
      PORTFOLIO_GANTT_SUBTITLE: 'Project timeline and execution status across all enterprise customers',
      PORTFOLIO_GANTT_TOTAL_CUSTOMERS: 'Total Customers',
      PORTFOLIO_GANTT_TOTAL_PROJECTS: 'Total Projects',
      PORTFOLIO_GANTT_ACTIVE: 'Active',
      PORTFOLIO_GANTT_DELAYED: 'Delayed',
      PORTFOLIO_GANTT_COMPLETED: 'Completed',
      PORTFOLIO_GANTT_EXPAND_ALL: 'Expand All',
      PORTFOLIO_GANTT_COLLAPSE_ALL: 'Collapse All',
      PORTFOLIO_GANTT_VIEW_MONTH: 'Month',
      PORTFOLIO_GANTT_VIEW_WEEK: 'Week',
      PORTFOLIO_GANTT_VIEW_DAY: 'Day',
      PORTFOLIO_GANTT_SEARCH_PLACEHOLDER: 'Search project, customer, or PM...',
      PORTFOLIO_GANTT_CUSTOMER_ALL: 'All Customers',
      PORTFOLIO_GANTT_STATUS_ALL: 'All Statuses',
      PORTFOLIO_GANTT_LEGEND_ON_TRACK: 'On Track',
      PORTFOLIO_GANTT_LEGEND_DELAYED: 'Behind Schedule',
      PORTFOLIO_GANTT_LEGEND_PLANNING: 'Planning',
      PORTFOLIO_GANTT_LEGEND_COMPLETED: 'Completed',
      PORTFOLIO_GANTT_NO_DATA: 'No project data found for current filters',
      PORTFOLIO_GANTT_VIEW_DETAILS: 'View Project Details',
      PORTFOLIO_GANTT_VIEW_BOARD: 'Open Task Board & Phase Gantt',
      PORTFOLIO_GANTT_PROJECTS_COUNT: '{{count}} projects',
      PMDT17A_CONTRACT_LABEL: 'Contract',
      PMDT17A_SELECT_CONTRACT_PLACEHOLDER: 'Select contract',
      PMDT16A_LBL_DELIVERY: 'Delivery',
      PMDT16A_PH_DELIVERY: 'Select delivery',
      PMDT14_GATE_CHECK_TITLE: 'Delivery Gate Check',
      PMDT14_CHECK_GATE_BTN: 'Re-check',
      PMDT14_CHECKING: 'Checking...',
      PMDT14_PASSED_MARK: 'Passed',
      PMDT14_FAILED_MARK: 'Action Required',
      PMDT14_VIEW_DATA: 'View Details',
      PMDT14_GO_MANAGE_PENDING: 'Manage Pending',
      PMDT14_GATE_STATUS_LABEL: 'Gate Check Status:',
      PMDT14_STATUS_READY: 'Ready to Deliver',
      PMDT14_HAS_CONDITIONS: 'Conditions Pending',
      PMDT14_PASSED_WORD: 'Passed',
      PMDT14_OUT_OF_WORD: 'out of',
      PMDT14_CHECKS_WORD: 'checks',
      PMDT14_GATE_EMPTY_HINT: 'Please select a contract or project to run delivery gate check',
      PMDT14_CLICK_TO_MANAGE_TIP: 'Click to manage items in this module',
      PMDT10_PAGE_DESC: 'Track real-time task progress and traceability',
      PMDT10_TOTAL_LABEL: 'Total',
      PMDT10_UNIT_TASK: 'Tasks',
      PMDT10_INPROGRESS_LABEL: 'In Progress',
      PMDT10_BUG_LABEL: 'Open Bugs',
      PMDT10_BUG_DONE_LABEL: 'Resolved Bugs',
      PMDT10_DONE_LABEL: 'Completed',
      PMDT10_CREATE_TASK_BTN: 'Create Task',
      PMDT10_NO_TASK_TITLE: 'No Tasks Yet',
      PMDT10_NO_TASK_DESC: 'Get started by creating a new task to track work progress',
      PMDT10_SELECT_PROJECT_MSG: 'No Tasks Yet',
      PMDT10_SELECT_PROJECT_HINT: 'Get started by creating a new task to track work progress',
      PMDT10_GO_PROJECT_LIST_BTN: 'Create Task',
      PMDT10_SEARCH_PH: 'Search task name, code...',
      PMDT10_SPEC_PH: 'All Specifications',
      PMDT10_WP_PH: 'All Work Packages',
      PMDT10_PRIORITY_PH: 'All Priorities',
      PMDT10_ASSIGNEE_PH: 'All Assignees',
      PMDT10_CLEAR_FILTER_BTN: 'Clear Filters',
      PMDT10_TABLE_VIEW_BTN: 'Table',
      PMDT10_LOADING_TASK: 'Loading tasks...',
      PMDT10_DELETE_TASK_TITLE: 'Delete Task',
      PMDT10_PRIO_CRITICAL: 'Critical',
      PMDT10_PRIO_HIGH: 'High',
      PMDT10_PRIO_MEDIUM: 'Medium',
      PMDT10_PRIO_LOW: 'Low',
      PMDT10_PRIO_CRITICAL_PLAIN: 'Critical',
      PMDT10_PRIO_HIGH_PLAIN: 'High',
      PMDT10_PRIO_MEDIUM_PLAIN: 'Medium',
      PMDT10_PRIO_LOW_PLAIN: 'Low',
      PMDT10_COL_TASK_CODE: 'Task Code',
      PMDT10_COL_TASK_NAME: 'Task Name',
      PMDT10_COL_ASSIGNEE: 'Assignee',
      PMDT10_COL_MANDAY: 'Manday (Actual / Est)',
      PMDT10_COL_STATUS: 'Status',
      PMDT10_COL_PRIORITY: 'Priority',
      PMDT10_COL_DUE_DATE: 'Due Date',
      PMDT10_COL_ACTIONS: 'Actions',
      PMDT10_EDIT_TASK_TITLE: 'Edit Task',
      PMDT10_NEW_TASK_TITLE: 'Create Task',
      PMDT10_MODAL_DESC: 'Fill in task details and assignees',
      PMDT10_SPEC_TRACE_LABEL: 'Specification (Traceability)',
      PMDT10_SPEC_SELECT_PH: 'Select Specification...',
      PMDT10_SPEC_REQUIRED_MSG: 'Please select a Specification',
      PMDT10_WP_LABEL: 'Work Package',
      PMDT10_WP_SELECT_PH: 'Select Work Package...',
      PMDT10_WP_REQUIRED_MSG: 'Please select a Work Package',
      PMDT10_TASK_CODE_LABEL: 'Task Code',
      PMDT10_TASK_CODE_PH: 'e.g. TSK-001',
      PMDT10_TASK_CODE_REQUIRED_MSG: 'Task code is required',
      PMDT10_TASK_NAME_LABEL: 'Task Name',
      PMDT10_TASK_NAME_PH: 'e.g. Develop User Interface',
      PMDT10_TASK_NAME_REQUIRED_MSG: 'Task name is required',
      PMDT10_TASK_DESC_LABEL: 'Description',
      PMDT10_TASK_DESC_PH: 'Describe task details...',
      PMDT10_ASSIGNEE_FIELD_LABEL: 'Assignee',
      PMDT10_ASSIGNEE_FIELD_PH: 'Select assignee...',
      PMDT10_START_DATE_LABEL: 'Start Date',
      PMDT10_START_DATE_PH: 'Select start date',
      PMDT10_START_TIME_LABEL: 'Start Time',
      PMDT10_END_DATE_LABEL: 'End Date',
      PMDT10_END_DATE_PH: 'Select end date',
      PMDT10_END_TIME_LABEL: 'End Time',
      PMDT10_TIME_PH: '09:00',
      PMDT10_ESTIMATE_MANDAY_LABEL: 'Estimate Manday',
      PMDT10_ACTUAL_MANDAY_LABEL: 'Actual Manday',
      PMDT10_PRIORITY_FIELD_LABEL: 'Priority',
      PMDT10_PRIORITY_SELECT_PH: 'Select priority',
      PMDT10_COLOR_TAG_LABEL: 'Color Tag',
      PMDT10_CANCEL_BTN: 'Cancel',
      PMDT10_SAVING_TEXT: 'Saving...',
      PMDT10_SAVE_EDIT_BTN: 'Save Changes',
      PMDT10_CONFIRM_DELETE_TITLE: 'Confirm Delete',
      PMDT10_CONFIRM_DELETE_MSG: 'Are you sure you want to delete this task?',
      PMDT10_DELETE_SUCCESS_TITLE: 'Deleted',
      PMDT10_DELETE_SUCCESS_MSG: 'Task has been deleted successfully',
      PMDT10_DELETE_ERROR_TITLE: 'Error',
      PMDT10_INCOMPLETE_DATA_TITLE: 'Incomplete Data',
      PMDT10_INCOMPLETE_DATA_MSG: 'Please fill in all required fields (*)',
      PMDT10_SAVE_SUCCESS_TITLE_A: 'Saved',
      PMDT10_CREATE_TASK_SUCCESS_MSG: 'Task created successfully',
      PMDT10_UPDATE_TASK_SUCCESS_MSG: 'Task updated successfully',
      PMDT10_SAVE_ERROR_TITLE_A: 'Save Failed',
      PMDT10_SAVE_TASK_ERROR_MSG: 'An error occurred while saving task',
      PMDT10_LOAD_FAIL_TITLE: 'Load Failed',
      PMDT10_LOAD_TASKS_FAIL_MSG: 'Could not load tasks',
      PMDT10_LOAD_BUGS_FAIL_MSG: 'Could not load bugs',
      PMDT10_NO_FILTER_RESULT_MSG: 'No tasks match your search criteria',
      PMDT09_PROJECT_LABEL: 'Project',
      PMDT09_PROJECT_PLACEHOLDER: 'Select project',
      PMDT09_REVIEW_CODE_LABEL: 'Review Code',
      PMDT09_REVIEW_CODE_PLACEHOLDER: 'e.g. DR-001',
      PMDT09_TITLE_LABEL: 'Review Title',
      PMDT09_TITLE_PLACEHOLDER: 'Enter review title',
      PMDT09_SEVERITY_FIELD_LABEL: 'Severity',
      PMDT09_SEV_SELECT_PH: 'Select severity',
      PMDT09_STATUS_LABEL: 'Status',
      PMDT09_STATUS_SELECT_PH: 'Select status',
      PMDT09_DUE_DATE_LABEL: 'Resolution Due Date',
      PMDT09_ASSIGNED_TO_LABEL: 'Assigned Fixer',
      PMDT09_ASSIGNED_TO_PH: 'Select assignee...',
      PMDT09_APPROVAL_FLOW_LABEL: 'Approval Flow',
      PMDT09_APPROVAL_FLOW_PH: 'Select approval flow...',
      PMDT09_DESC_LABEL: 'Description',
      PMDT09_DESC_PLACEHOLDER: 'Enter review details, comments or improvements...',
      PMDT09_FIGMA_URL_LABEL: 'Figma File / Prototype URL',
      PMDT09_FIGMA_URL_PH: 'https://www.figma.com/file/...',
      PMDT09_PAGE_TITLE: 'Design Review',
      PMDT09_PAGE_DESC: 'Review and approve UI/UX designs from Figma and prototypes',
      PMDT09_CREATE_BTN: 'Create Design Review',
      PMDT09_SEARCH_PLACEHOLDER: 'Search code, title, creator...',
      PMDT09_STATUS_PLACEHOLDER: 'All Statuses',
      PMDT09_TYPE_PLACEHOLDER: 'All Types',
      PMDT09_SEVERITY_PLACEHOLDER: 'All Severities',
      PMDT09_EMPTY_TITLE: 'No Design Reviews Found',
      PMDT09_EMPTY_DESC: 'Get started by creating a new design review to inspect screens and flows',
      PMDT09_CANCEL_BTN: 'Cancel',
      PMDT09_SAVE_BTN: 'Save',
      PMDT09_SUBMIT_APPROVAL_BTN: 'Submit for Approval',
      PMDT03_PAGE_TITLE: 'Approval Center',
      PMDT03_SUBTITLE: 'Manage approval workflows and pending requests',
      PMDT03_MY_PENDING_TITLE: 'Pending My Approval',
      PMDT03_OVERDUE_TITLE: 'Overdue Approvals',
      PMDT03_ALL_STATUS_PLACEHOLDER: 'All Statuses',
      PMDT03_SELECT_PROJECT_PLACEHOLDER: 'Select Project',
      PMDT03_COL_TYPE_CODE: 'Document Type / Code',
      PMDT03_COL_ITEM: 'Title / Subject',
      PMDT03_COL_PROJECT: 'Project',
      PMDT03_COL_REQUESTER: 'Requester',
      PMDT03_COL_REQUESTED_DATE: 'Requested Date',
      PMDT03_COL_STATUS: 'Status',
      PMDT03_COL_ACTIONS: 'Actions',
      PMDT03_STATUS_PENDING: 'Pending',
      PMDT03_STATUS_APPROVED: 'Approved',
      PMDT03_STATUS_REJECTED: 'Rejected',
      PMDT03_STATUS_NEED_REVISION_OPT: 'Need Revision',
      PMDT03_STATUS_CANCELLED: 'Cancelled',
      PMDT03_PROJECT_CRM: 'Customer Relationship Management (CRM)',
      PMDT03_PROJECT_HR: 'Human Resource Management (HRMS)',
      PMDT03_ITEMS_SUFFIX: 'items',
      PMDT03_ITEMS_UNIT: 'items',
      PMDT03_NO_USER_TITLE: 'User Info Not Found',
      PMDT03_RELOGIN_MSG: 'Please sign in again',
      PMDT05_REQUIREMENT_LABEL: 'Requirement',
      PMDT05_REQUIREMENT_PLACEHOLDER: 'Select related requirement (optional)',
      PMDT05_REQ_SOURCE_LABEL: 'Source Requirement:',
      PMDT07_REQUIREMENT_LABEL: 'Requirement',
      PMDT07_REQUIREMENT_PLACEHOLDER: 'Select Requirement',
      PMDT07_SPEC_CODE_LABEL: 'Specification Code',
      PMDT07_SPEC_CODE_PLACEHOLDER: 'e.g. SPEC-001',
      PMDT07_SPEC_TYPE_LABEL: 'Specification Type',
      PMDT07_SPEC_TYPE_PLACEHOLDER: 'Select Specification Type',
      PMDT07_TITLE_LABEL: 'Specification Title',
      PMDT07_TITLE_PLACEHOLDER: 'Enter title',
      PMDT07_PRIORITY_LABEL: 'Priority',
      PMDT07_PRIORITY_PLACEHOLDER: 'Select Priority',
      PMDT07_ASSIGNEE_LABEL: 'Assignee',
      PMDT07_ASSIGNEE_PLACEHOLDER: 'Select Assignee',
      PMDT07_ESTIMATED_MANDAY_LABEL: 'Estimated Manday',
      PMDT07_ESTIMATED_MANDAY_PLACEHOLDER: 'Enter manday',
      PMDT07_DESC_LABEL: 'Specification Description',
      PMDT07_DESC_PLACEHOLDER: 'Type description here...',
      PMDT07_ATTACHMENTS_LABEL: 'Attachments',
      PMDT07_ATTACHMENTS_HELPER: 'Drag & drop files here, or click to browse',
      PMDT07_CREATE_SPEC_TITLE: 'Create Specification',
      PMDT07_EDIT_SPEC_TITLE: 'Edit Specification',
      PMDT07_VIEW_SPEC_TITLE: 'Specification Details',
      PMDT07_CANCEL_BTN: 'Cancel',
      PMDT07_SAVE_BTN: 'Save',
      PMDT07_SUBMIT_BTN: 'Submit for Approval',
      PMDT07_HEADER_TITLE: 'Specification',
      PMDT01_CREATE_PHASE_TITLE: 'Create Phase',
      PMDT01_EDIT_PHASE_TITLE: 'Edit Phase',
      PMDT01_EMPTY_TITLE: 'No Phases in this Project',
      PMDT01_EMPTY_HINT: 'Get started by clicking "+ Add Phase" above to plan project phases and milestones.',
      PMDT01_CUSTOMER_LABEL: 'Customer',
      PMDT01_CUSTOMER_PLACEHOLDER: 'Search and select customer',
      PMDT01_PROJECT_LABEL: 'Project',
      PMDT01_PROJECT_PLACEHOLDER: 'Search and select project',
      PMDT02_CREATE_MS_TITLE_H: 'Create Milestone',
      PMDT02_EDIT_MS_TITLE_H: 'Edit Milestone',
      PMDT02_PHASE_LABEL: 'Phase',
      PMDT02_SELECT_PHASE_PLACEHOLDER: 'Search and select phase',
      PMDT02_CREATE_WP_TITLE_H: 'Create Work Package',
      PMDT02_EDIT_WP_TITLE_H: 'Edit Work Package',
      PMDT02_MILESTONE_LABEL: 'Milestone',
      PMDT02_SELECT_MILESTONE_PLACEHOLDER: 'Search and select milestone',
      PMDT02_CREATE_TASK_TITLE_H: 'Create Task',
      PMDT02_EDIT_TASK_TITLE_H: 'Edit Task',
      PMDT02_WORK_PACKAGE_LABEL: 'Work Package',
      PMDT02_SELECT_WP_PLACEHOLDER: 'Search and select work package',
      PMDT06_CUSTOMER_LABEL: 'Customer',
      PMDT06_CUSTOMER_PLACEHOLDER: 'Search and select customer',
      PMDT06_PROJECT_LABEL: 'Project',
      PMDT06_PROJECT_PLACEHOLDER: 'Search and select project',
      PMDT06_UPSTREAM_CONTEXT_LABEL: 'Impacted Projects & Customers (Upstream)',
      PMDT06_IMPACT_CUSTOMERS_LABEL: 'Impacted Customers',
      PMDT06_IMPACT_PROJECTS_LABEL: 'Impacted Projects',
      PMDT06_IMPACT_REQUIREMENT: 'Requirements',
      PMDT06_IMPACT_SPECIFICATION: 'Specifications',
      PMDT06_IMPACT_DIAGRAM: 'Diagrams',
      PMDT06_IMPACT_TASK: 'Tasks',
      PMDT06_IMPACT_TESTCASE: 'Test Cases',
      PMDT06_IMPACT_TESTPLAN: 'Test Plans',
      PMDT06_IMPACT_BUG: 'Bugs',
      PMDT06_IMPACT_CONTRACT: 'Contracts',
      PMDT06_IMPACT_DESIGNREVIEW: 'Design Reviews',
      PMDT06_IMPACT_DELIVERY: 'Deliveries',
      PMDT06_IMPACT_USERMANUAL: 'User Manuals',
      PMDT06_IMPACT_INVOICE: 'Invoices & Payments',
      PMDT06_IMPACT_MATICKET: 'MA Tickets',
      PMDT06_IMPACT_MARENEWAL: 'MA Renewals',
      PMDT12_SEARCH_PLACEHOLDER: 'Search scenario, case code, title, tester...',
      PMDT12_FILTER_STATUS_PH: '📊 All Test Case Statuses',
      PMDT12_FILTER_PRIORITY_PH: '⚡ All Priorities',
      PMDT12_FILTER_TASK_STATUS_PH: '🎯 All Task Statuses',
      PMDT12_SEVERITY_LABEL: 'Severity',
      PMDT12_SEVERITY_PH: 'Select severity',
      PMDT12_BUG_TITLE_LABEL: 'Bug Title / Summary',
      PMDT12_BUG_TITLE_PH: 'Enter bug details...',
      PMDT12_ASSIGNED_TO_LABEL: 'Assigned Fixer',
      PMDT12_ASSIGNED_TO_PH: 'Select assignee',
      PMDT12_MANDAY_LABEL: 'Estimated Manday',
      PMDT12B_TASK_TRACE_LABEL: 'Task',
      PMDT12B_TASK_TRACE_PLACEHOLDER: 'Select Task',
      PMDT12B_SCENARIO_CODE_LABEL: 'Test Scenario Code',
      PMDT12B_SCENARIO_CODE_PLACEHOLDER: 'e.g. SC-001, SC-LOGIN',
      PMDT12B_SCENARIO_NAME_LABEL: 'Test Scenario Name',
      PMDT12B_SCENARIO_NAME_PLACEHOLDER: 'e.g. Login, Report printing...',
      PMDT12B_TEST_TYPE_LABEL: 'Test Type',
      PMDT12B_TEST_TYPE_PLACEHOLDER: 'Select test type',
      PMDT12B_PRIORITY_LABEL: 'Priority',
      PMDT12B_PRIORITY_PLACEHOLDER: 'Select priority level',
      PMDT12B_DESCRIPTION_LABEL: 'Description / Scenario Purpose',
      PMDT12B_DESCRIPTION_PLACEHOLDER: 'Describe the scope and objective of testing for this group...',
      PMDT12B_RICH_TEXT_HINT: 'Rich text formatting supported',
      PMDT12B_STATUS_ACTIVE_LABEL: 'Active',
    },
  };

  private initPromise: Promise<any> | null = null;

  initLanguage(): Promise<any> {
    if (this.initPromise) {
      return this.initPromise;
    }
    this.translate.setTranslation('th', this.defaultTranslations.th, true);
    this.translate.setTranslation('en', this.defaultTranslations.en, true);
    const lang = this.resolveInitialLanguage();
    this.updateHtmlLang(lang);

    this.initPromise = firstValueFrom(this.translate.use(lang)).catch((err) => {
      console.error('Failed to load translations:', err);
      return null;
    });

    return this.initPromise;
  }

  setLanguage(lang: AppLanguage): void {
    if (isPlatformBrowser(this.platformId)) {
      localStorage.setItem(this.storageKey, lang);
    }

    this.translate.use(lang);
    this.updateHtmlLang(lang);

    // Reload page to refresh all components and dynamic labels according to chosen language
    if (isPlatformBrowser(this.platformId)) {
      window.location.reload();
    }
  }

  getCurrentLanguage(): AppLanguage {
    const current = this.translate.getCurrentLang();
    return (current === 'th' || current === 'en') ? current : 'en';
  }

  private resolveInitialLanguage(): AppLanguage {
    if (isPlatformBrowser(this.platformId)) {
      const saved = localStorage.getItem(this.storageKey);
      if (saved === 'th' || saved === 'en') return saved;
      const browserLang = navigator.language || '';
      return browserLang.toLowerCase().startsWith('th') ? 'th' : 'en';
    }
    return 'en';
  }

  private updateHtmlLang(lang: AppLanguage): void {
    const html = this.document.documentElement;
    html.lang = lang;
    html.dir = 'ltr';
  }
}