import { Injectable, inject, PLATFORM_ID } from '@angular/core';
import { DOCUMENT, isPlatformBrowser } from '@angular/common';
import { firstValueFrom, Observable } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { DateTimeUtil } from '../utils/datetime.util';

export type AppLanguage = 'th' | 'en';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly document = inject(DOCUMENT);
  private readonly platformId = inject(PLATFORM_ID);
  private readonly translate = inject(TranslateService);
  private readonly storageKey = 'app-lang';

  constructor() {
    this.translate.onLangChange.subscribe(({ lang }) => {
      this.updateHtmlLang(lang as AppLanguage);
    });
  }

  private readonly defaultTranslations: Record<'th' | 'en', Record<string, string>> = {
    th: {
      COMMON_UNSAVED_CHANGES_TITLE: 'มีการเปลี่ยนแปลงที่ยังไม่บันทึก',
      COMMON_UNSAVED_CHANGES_MSG: 'คุณมีการเปลี่ยนแปลงที่ยังไม่บันทึก ต้องการออกจากหน้านี้หรือไม่?',
      DASHBOARD_CHIP_ACTIVE_PROJECTS: 'โครงการดำเนินงาน',
      DASHBOARD_CHIP_PENDING_APPROVALS: 'รออนุมัติ',
      DASHBOARD_CHIP_OPEN_BUGS: 'บั๊กค้าง',
      DASHBOARD_CHIP_EXPIRING_CONTRACTS: 'สัญญาใกล้หมดอายุ',
      CONTEXT_SWITCHER_TITLE: 'ตัวกรองและสลับโปรเจกต์',
      CONTEXT_SWITCHER_POPOVER_TITLE: 'ค้นหา & สลับโปรเจกต์',
      CONTEXT_SWITCHER_POPOVER_SUBTITLE: 'คัดกรองและเลือกโปรเจกต์การทำงาน',
      CONTEXT_SWITCHER_SELECT_PROMPT: 'เลือกโปรเจกต์ / ตัวกรอง...',
      CONTEXT_SWITCHER_CUSTOMER_SELECTED: 'เลือกลูกค้าแล้ว (ยังไม่เลือกโปรเจกต์)',
      CONTEXT_SWITCHER_SELECTED_PROJECT: 'โปรเจกต์ที่เลือก',
      CONTEXT_SWITCHER_PROJECTS_SELECTED: 'โปรเจกต์ที่เลือก',
      CONTEXT_SWITCHER_SEARCH_PLACEHOLDER: 'ค้นหาชื่อโปรเจกต์, รหัสโปรเจกต์...',
      CONTEXT_SWITCHER_CUSTOMER_LABEL: 'ลูกค้า',
      CONTEXT_SWITCHER_CUSTOMER_SEARCH_PLACEHOLDER: 'พิมพ์ค้นหาลูกค้า...',
      CONTEXT_SWITCHER_CUSTOMER_NOT_FOUND: 'ไม่พบรายชื่อลูกค้า',
      CONTEXT_SWITCHER_ALL_CUSTOMERS: 'ทุกลูกค้า (ทั้งหมด)',
      CONTEXT_SWITCHER_STATUS_LABEL: 'สถานะงาน',
      CONTEXT_SWITCHER_PRIORITY_LABEL: 'ระดับความสำคัญ',
      CONTEXT_SWITCHER_MATCHING_PROJECTS: 'โปรเจกต์ที่ตรงเงื่อนไข',
      CONTEXT_SWITCHER_LOADING_PROJECTS: 'กำลังโหลดรายการโปรเจกต์...',
      CONTEXT_SWITCHER_NO_MATCHING_PROJECTS: 'ไม่พบโปรเจกต์ตามเงื่อนไขตัวกรอง',
      CONTEXT_SWITCHER_CURRENT: 'ปัจจุบัน',
      CONTEXT_SWITCHER_SWITCH: 'สลับ',
      CONTEXT_SWITCHER_RESET_FILTERS: 'ล้างตัวกรอง',
      CONTEXT_SWITCHER_CLEAR_CONTEXT: 'ล้างบริบทปัจจุบัน',
      CONTEXT_SWITCHER_CLOSE: 'ปิด',
      CONTEXT_SWITCHER_SELECT_ALL: 'เลือกทั้งหมด',
      CONTEXT_SWITCHER_UNSELECT_ALL: 'ยกเลิกทั้งหมด',
      STATUS_ALL: 'ทั้งหมด',
      STATUS_PLANNING: 'วางแผน',
      STATUS_DEVELOPMENT: 'กำลังพัฒนา',
      STATUS_UAT: 'ทดสอบ',
      STATUS_BUG_FIXING: 'แก้ไขบั๊ก',
      STATUS_DELIVERED: 'ส่งมอบแล้ว',
      STATUS_CLOSED: 'ปิดงาน',
      PRIORITY_ALL: 'ทั้งหมด',
      PRIORITY_CRITICAL: 'ด่วนมาก',
      PRIORITY_HIGH: 'สูง',
      PRIORITY_MEDIUM: 'ปานกลาง',
      PRIORITY_LOW: 'ต่ำ',
      PRIORITY_NORMAL: 'ทั่วไป',
      PROJECT_HEALTH_WIDGET_TITLE: 'สุขภาพโครงการ',
      PROJECT_HEALTH_STATUS_GOOD: 'สุขภาพดี',
      PROJECT_HEALTH_STATUS_WARNING: 'เฝ้าระวัง',
      PROJECT_HEALTH_STATUS_CRITICAL: 'วิกฤต',
      PROJECT_HEALTH_TOTAL_SCORE: 'คะแนนสุขภาพรวม',
      PROJECT_HEALTH_FACTOR_TASKS: 'ความคืบหน้างาน',
      PROJECT_HEALTH_FACTOR_MANDAY: 'การใช้ Manday (จากงบทั้งหมด)',
      PROJECT_HEALTH_FACTOR_QUALITY: 'คุณภาพ & การแก้ไข Bug',
      PROJECT_HEALTH_FACTOR_PHASE: 'ความคืบหน้า Phase',
      PROJECT_HEALTH_FACTOR_TIMELINE: 'สถานะและกำหนดการ',
      PROJECT_HEALTH_DETAIL_NO_TASKS: 'ไม่มีงาน (0/0)',
      PROJECT_HEALTH_DETAIL_TASKS_PROGRESS: 'งานเสร็จ {{completed}}/{{total}} งาน ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_MANDAY_USAGE: '{{used}} / {{budget}} Manday ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_NO_BUGS: 'สมบูรณ์ ไม่มี Bug ในระบบ (0/0)',
      PROJECT_HEALTH_DETAIL_BUGS_PROGRESS: 'แก้ไขแล้ว {{closed}}/{{total}} Bug ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_NO_PHASES: 'ไม่มี Phase (0/0)',
      PROJECT_HEALTH_DETAIL_PHASES_PROGRESS: '{{completed}}/{{total}} Phase ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_ON_SCHEDULE: 'ตามแผนงาน',
      PROJECT_HEALTH_DETAIL_DELAYED: 'ล่าช้ากว่ากำหนด',
      PROJECT_HEALTH_DETAIL_COMPLETED: 'เสร็จสิ้นตามเป้าหมาย',
      PROJECT_HEALTH_DETAIL_OVERDUE: 'เกินกำหนดส่งมอบ',
      PORTFOLIO_GANTT_TITLE: 'ผังระยะเวลาโครงการองค์กร (Enterprise Portfolio Roadmap)',
      PORTFOLIO_GANTT_SUBTITLE: 'แสดงระยะเวลาและสถานะดำเนินงานทุกโครงการ แยกตามลูกค้ารายองค์กร',
      PORTFOLIO_GANTT_TOTAL_CUSTOMERS: 'ลูกค้าทั้งหมด',
      PORTFOLIO_GANTT_TOTAL_PROJECTS: 'โครงการทั้งหมด',
      PORTFOLIO_GANTT_ACTIVE: 'กำลังดำเนินงาน',
      PORTFOLIO_GANTT_DELAYED: 'ล่าช้ากว่าแผน',
      PORTFOLIO_GANTT_COMPLETED: 'เสร็จสิ้นแล้ว',
      PORTFOLIO_GANTT_EXPAND_ALL: 'ขยายทั้งหมด',
      PORTFOLIO_GANTT_COLLAPSE_ALL: 'พับทั้งหมด',
      PORTFOLIO_GANTT_VIEW_MONTH: 'รายเดือน',
      PORTFOLIO_GANTT_VIEW_WEEK: 'รายสัปดาห์',
      PORTFOLIO_GANTT_VIEW_DAY: 'รายวัน',
      PORTFOLIO_GANTT_SEARCH_PLACEHOLDER: 'ค้นหาโครงการ, ลูกค้า, หรือ PM...',
      PORTFOLIO_GANTT_CUSTOMER_ALL: 'ทุกลูกค้า (All Customers)',
      PORTFOLIO_GANTT_STATUS_ALL: 'ทุกสถานะ',
      PORTFOLIO_GANTT_LEGEND_ON_TRACK: 'ตามแผนงาน',
      PORTFOLIO_GANTT_LEGEND_DELAYED: 'ล่าช้ากว่ากำหนด',
      PORTFOLIO_GANTT_LEGEND_PLANNING: 'กำลังวางแผน',
      PORTFOLIO_GANTT_LEGEND_COMPLETED: 'เสร็จสิ้น',
      PORTFOLIO_GANTT_NO_DATA: 'ไม่พบข้อมูลโครงการตามเงื่อนไขตัวกรอง',
      PORTFOLIO_GANTT_VIEW_DETAILS: 'ดูรายละเอียดโครงการ',
      PORTFOLIO_GANTT_VIEW_BOARD: 'เปิด Task Board & Phase Gantt',
      PORTFOLIO_GANTT_PROJECTS_COUNT: '{{count}} โครงการ',
      PMDT17A_CONTRACT_LABEL: 'สัญญา',
      PMDT17A_SELECT_CONTRACT_PLACEHOLDER: 'เลือกสัญญา',
      PMDT16A_LBL_DELIVERY: 'Delivery',
      PMDT16A_PH_DELIVERY: 'เลือก Delivery',
      PMDT14_GATE_CHECK_TITLE: 'การตรวจสอบความพร้อมส่งมอบ',
      PMDT14_CHECK_GATE_BTN: 'ตรวจสอบใหม่',
      PMDT14_CHECKING: 'กำลังตรวจสอบ...',
      PMDT14_PASSED_MARK: 'ผ่าน',
      PMDT14_FAILED_MARK: 'ต้องดำเนินการ',
      PMDT14_VIEW_DATA: 'ดูรายละเอียด',
      PMDT14_GO_MANAGE_PENDING: 'ไปจัดการรายการค้าง',
      PMDT14_GATE_STATUS_LABEL: 'สถานะ Gate Check:',
      PMDT14_STATUS_READY: 'พร้อมส่งมอบ',
      PMDT14_HAS_CONDITIONS: 'ยังมีเงื่อนไขที่ต้องแก้ไข',
      PMDT14_PASSED_WORD: 'ผ่าน',
      PMDT14_OUT_OF_WORD: 'จากทั้งหมด',
      PMDT14_CHECKS_WORD: 'ข้อกำหนด',
      PMDT14_GATE_EMPTY_HINT: 'กรุณาเลือกสัญญาหรือโครงการเพื่อตรวจสอบความพร้อมส่งมอบ',
      PMDT14_CLICK_TO_MANAGE_TIP: 'คลิกเพื่อไปจัดการข้อมูลในโมดูลนี้',
      PMDT10_PAGE_DESC: 'ติดตามสถานะงานจริงและ Traceability',
      PMDT10_TOTAL_LABEL: 'ทั้งหมด',
      PMDT10_UNIT_TASK: 'งาน',
      PMDT10_INPROGRESS_LABEL: 'กำลังทำ',
      PMDT10_BUG_LABEL: 'Bug ค้าง',
      PMDT10_BUG_DONE_LABEL: 'Bug เสร็จ',
      PMDT10_DONE_LABEL: 'เสร็จสิ้น',
      PMDT10_CREATE_TASK_BTN: 'สร้าง Task',
      PMDT10_NO_TASK_TITLE: 'ยังไม่มี Task ในระบบ',
      PMDT10_NO_TASK_DESC: 'เริ่มต้นด้วยการสร้าง Task เพื่อจัดการงานและติดตามความคืบหน้า',
      PMDT10_SELECT_PROJECT_MSG: 'ยังไม่มี Task ในระบบ',
      PMDT10_SELECT_PROJECT_HINT: 'เริ่มต้นด้วยการสร้าง Task เพื่อจัดการงานและติดตามความคืบหน้า',
      PMDT10_GO_PROJECT_LIST_BTN: 'สร้าง Task',
      PMDT10_SEARCH_PH: 'ค้นหาชื่อ Task, รหัสงาน...',
      PMDT10_SPEC_PH: 'ทุก Specification',
      PMDT10_WP_PH: 'ทุก Work Package',
      PMDT10_PRIORITY_PH: 'ทุกความสำคัญ',
      PMDT10_ASSIGNEE_PH: 'ทุกผู้รับผิดชอบ',
      PMDT10_CLEAR_FILTER_BTN: 'ล้างตัวกรอง',
      PMDT10_TABLE_VIEW_BTN: 'ตาราง',
      PMDT10_LOADING_TASK: 'กำลังโหลดข้อมูล Task...',
      PMDT10_DELETE_TASK_TITLE: 'ลบ Task',
      PMDT10_PRIO_CRITICAL: 'วิกฤต',
      PMDT10_PRIO_HIGH: 'สูง',
      PMDT10_PRIO_MEDIUM: 'ปานกลาง',
      PMDT10_PRIO_LOW: 'ต่ำ',
      PMDT10_PRIO_CRITICAL_PLAIN: 'วิกฤต',
      PMDT10_PRIO_HIGH_PLAIN: 'สูง',
      PMDT10_PRIO_MEDIUM_PLAIN: 'ปานกลาง',
      PMDT10_PRIO_LOW_PLAIN: 'ต่ำ',
      PMDT10_COL_TASK_CODE: 'รหัส Task',
      PMDT10_COL_TASK_NAME: 'ชื่องาน',
      PMDT10_COL_ASSIGNEE: 'ผู้รับผิดชอบ',
      PMDT10_COL_MANDAY: 'Manday (จริง / ประเมิน)',
      PMDT10_COL_STATUS: 'สถานะ',
      PMDT10_COL_PRIORITY: 'ความสำคัญ',
      PMDT10_COL_DUE_DATE: 'วันครบกำหนด',
      PMDT10_COL_ACTIONS: 'จัดการ',
      PMDT10_EDIT_TASK_TITLE: 'แก้ไข Task',
      PMDT10_NEW_TASK_TITLE: 'สร้าง Task',
      PMDT10_MODAL_DESC: 'กรอกรายละเอียดงานและผู้รับผิดชอบ',
      PMDT10_SPEC_TRACE_LABEL: 'Specification (Traceability)',
      PMDT10_SPEC_SELECT_PH: 'เลือก Specification...',
      PMDT10_SPEC_REQUIRED_MSG: 'กรุณาเลือก Specification',
      PMDT10_WP_LABEL: 'Work Package',
      PMDT10_WP_SELECT_PH: 'เลือก Work Package...',
      PMDT10_WP_REQUIRED_MSG: 'กรุณาเลือก Work Package',
      PMDT10_TASK_CODE_LABEL: 'รหัส Task',
      PMDT10_TASK_CODE_PH: 'เช่น TSK-001',
      PMDT10_TASK_CODE_REQUIRED_MSG: 'กรุณากรอกรหัส Task',
      PMDT10_TASK_NAME_LABEL: 'ชื่องาน',
      PMDT10_TASK_NAME_PH: 'เช่น พัฒนาระบบส่วนติดต่อผู้ใช้',
      PMDT10_TASK_NAME_REQUIRED_MSG: 'กรุณากรอกชื่องาน',
      PMDT10_TASK_DESC_LABEL: 'รายละเอียดงาน',
      PMDT10_TASK_DESC_PH: 'อธิบายรายละเอียดของงาน...',
      PMDT10_ASSIGNEE_FIELD_LABEL: 'ผู้รับผิดชอบหลัก',
      PMDT10_ASSIGNEE_FIELD_PH: 'เลือกผู้รับผิดชอบ...',
      PMDT10_START_DATE_LABEL: 'วันที่เริ่ม',
      PMDT10_START_DATE_PH: 'เลือกวันที่เริ่ม',
      PMDT10_START_TIME_LABEL: 'เวลาเริ่ม',
      PMDT10_END_DATE_LABEL: 'วันที่สิ้นสุด',
      PMDT10_END_DATE_PH: 'เลือกวันที่สิ้นสุด',
      PMDT10_END_TIME_LABEL: 'เวลาสิ้นสุด',
      PMDT10_TIME_PH: '09:00',
      PMDT10_ESTIMATE_MANDAY_LABEL: 'ประมาณการ Manday',
      PMDT10_ACTUAL_MANDAY_LABEL: 'Manday ที่ใช้จริง',
      PMDT10_PRIORITY_FIELD_LABEL: 'ระดับความสำคัญ',
      PMDT10_PRIORITY_SELECT_PH: 'เลือกระดับความสำคัญ',
      PMDT10_COLOR_TAG_LABEL: 'แท็กสี',
      PMDT10_CANCEL_BTN: 'ยกเลิก',
      PMDT10_SAVING_TEXT: 'กำลังบันทึก...',
      PMDT10_SAVE_EDIT_BTN: 'บันทึกการแก้ไข',
      PMDT10_CONFIRM_DELETE_TITLE: 'ยืนยันการลบ',
      PMDT10_CONFIRM_DELETE_MSG: 'คุณต้องการลบ Task นี้หรือไม่?',
      PMDT10_DELETE_SUCCESS_TITLE: 'ลบสำเร็จ',
      PMDT10_DELETE_SUCCESS_MSG: 'ลบ Task เรียบร้อยแล้ว',
      PMDT10_DELETE_ERROR_TITLE: 'เกิดข้อผิดพลาด',
      PMDT10_INCOMPLETE_DATA_TITLE: 'ข้อมูลไม่ครบถ้วน',
      PMDT10_INCOMPLETE_DATA_MSG: 'กรุณากรอกข้อมูลในช่องที่จำเป็น (*) ให้ครบถ้วน',
      PMDT10_SAVE_SUCCESS_TITLE_A: 'บันทึกสำเร็จ',
      PMDT10_CREATE_TASK_SUCCESS_MSG: 'สร้าง Task เรียบร้อยแล้ว',
      PMDT10_UPDATE_TASK_SUCCESS_MSG: 'บันทึกการแก้ไข Task เรียบร้อยแล้ว',
      PMDT10_SAVE_ERROR_TITLE_A: 'บันทึกไม่สำเร็จ',
      PMDT10_SAVE_TASK_ERROR_MSG: 'เกิดข้อผิดพลาดในการบันทึก Task',
      PMDT10_LOAD_FAIL_TITLE: 'โหลดข้อมูลไม่สำเร็จ',
      PMDT10_LOAD_TASKS_FAIL_MSG: 'ไม่สามารถโหลดข้อมูล Task ได้',
      PMDT10_LOAD_BUGS_FAIL_MSG: 'ไม่สามารถโหลดข้อมูล Bug ได้',
      PMDT10_NO_FILTER_RESULT_MSG: 'ไม่พบ Task ที่ตรงกับเงื่อนไขการค้นหา',
      PMDT09_PROJECT_LABEL: 'โครงการ',
      PMDT09_PROJECT_PLACEHOLDER: 'เลือกโครงการ',
      PMDT09_REVIEW_CODE_LABEL: 'รหัส Design Review',
      PMDT09_REVIEW_CODE_PLACEHOLDER: 'เช่น DR-001',
      PMDT09_TITLE_LABEL: 'หัวข้อการตรวจทาน',
      PMDT09_TITLE_PLACEHOLDER: 'ระบุหัวข้อการตรวจทาน',
      PMDT09_SEVERITY_FIELD_LABEL: 'ระดับความรุนแรง',
      PMDT09_SEV_SELECT_PH: 'เลือกระดับความรุนแรง',
      PMDT09_STATUS_LABEL: 'สถานะ',
      PMDT09_STATUS_SELECT_PH: 'เลือกสถานะ',
      PMDT09_DUE_DATE_LABEL: 'กำหนดเสร็จ',
      PMDT09_ASSIGNED_TO_LABEL: 'ผู้รับผิดชอบแก้ไข',
      PMDT09_ASSIGNED_TO_PH: 'เลือกผู้รับผิดชอบ...',
      PMDT09_APPROVAL_FLOW_LABEL: 'ขั้นตอนการอนุมัติ',
      PMDT09_APPROVAL_FLOW_PH: 'เลือกขั้นตอนการอนุมัติ...',
      PMDT09_DESC_LABEL: 'รายละเอียดการตรวจทาน',
      PMDT09_DESC_PLACEHOLDER: 'ระบุรายละเอียด ข้อคิดเห็น หรือจุดที่ต้องปรับปรุง...',
      PMDT09_FIGMA_URL_LABEL: 'Figma File / Prototype URL',
      PMDT09_FIGMA_URL_PH: 'https://www.figma.com/file/...',
      PMDT09_PAGE_TITLE: 'การตรวจทานการออกแบบ (Design Review)',
      PMDT09_PAGE_DESC: 'ศูนย์รวมการตรวจทานและอนุมัติแบบ UI/UX จาก Figma และ Prototype',
      PMDT09_CREATE_BTN: 'สร้าง Design Review',
      PMDT09_SEARCH_PLACEHOLDER: 'ค้นหารหัส, ชื่องาน, ผู้สร้าง...',
      PMDT09_STATUS_PLACEHOLDER: 'ทุกสถานะ',
      PMDT09_TYPE_PLACEHOLDER: 'ทุกประเภท',
      PMDT09_SEVERITY_PLACEHOLDER: 'ทุกระดับความรุนแรง',
      PMDT09_EMPTY_TITLE: 'ยังไม่มี Design Review ในระบบ',
      PMDT09_EMPTY_DESC: 'เริ่มต้นด้วยการสร้าง Design Review ใหม่ เพื่อตรวจสอบความถูกต้องของหน้าจอ',
      PMDT09_CANCEL_BTN: 'ยกเลิก',
      PMDT09_SAVE_BTN: 'บันทึก',
      PMDT09_SUBMIT_APPROVAL_BTN: 'ส่งขออนุมัติ',
      PMDT03_PAGE_TITLE: 'ศูนย์การอนุมัติ',
      PMDT03_SUBTITLE: 'จัดการสายการอนุมัติและรายการรออนุมัติ',
      PMDT03_MY_PENDING_TITLE: 'รอฉันอนุมัติ',
      PMDT03_OVERDUE_TITLE: 'รายการเกินกำหนด',
      PMDT03_ALL_STATUS_PLACEHOLDER: 'ทุกสถานะ',
      PMDT03_SELECT_PROJECT_PLACEHOLDER: 'เลือกโครงการ',
      PMDT03_COL_TYPE_CODE: 'ประเภท / รหัสเอกสาร',
      PMDT03_COL_ITEM: 'หัวข้อ / รายการ',
      PMDT03_COL_PROJECT: 'โครงการ',
      PMDT03_COL_REQUESTER: 'ผู้ยื่นคำขอ',
      PMDT03_COL_REQUESTED_DATE: 'วันที่ยื่นขอ',
      PMDT03_COL_STATUS: 'สถานะ',
      PMDT03_COL_ACTIONS: 'จัดการ',
      PMDT03_STATUS_PENDING: 'รอดำเนินการ',
      PMDT03_STATUS_APPROVED: 'อนุมัติแล้ว',
      PMDT03_STATUS_REJECTED: 'ปฏิเสธ',
      PMDT03_STATUS_NEED_REVISION_OPT: 'ต้องแก้ไข',
      PMDT03_STATUS_CANCELLED: 'ยกเลิก',
      PMDT03_PROJECT_CRM: 'ระบบจัดการลูกค้าสัมพันธ์ (CRM)',
      PMDT03_PROJECT_HR: 'ระบบบริหารงานบุคคล (HRMS)',
      PMDT03_ITEMS_SUFFIX: 'รายการ',
      PMDT03_ITEMS_UNIT: 'รายการ',
      PMDT03_NO_USER_TITLE: 'ไม่พบข้อมูลผู้ใช้',
      PMDT03_RELOGIN_MSG: 'กรุณาเข้าสู่ระบบใหม่',
      PMDT07_REQUIREMENT_LABEL: 'ความต้องการ',
      PMDT07_REQUIREMENT_PLACEHOLDER: 'เลือก Requirement',
      PMDT07_SPEC_CODE_LABEL: 'รหัส Specification',
      PMDT07_SPEC_CODE_PLACEHOLDER: 'เช่น SPEC-001',
      PMDT07_SPEC_TYPE_LABEL: 'ประเภท Specification',
      PMDT07_SPEC_TYPE_PLACEHOLDER: 'เลือกประเภท Specification',
      PMDT07_TITLE_LABEL: 'ชื่อเอกสาร Specification',
      PMDT07_TITLE_PLACEHOLDER: 'ระบุชื่อ Specification',
      PMDT07_PRIORITY_LABEL: 'ความสำคัญ',
      PMDT07_PRIORITY_PLACEHOLDER: 'เลือกระดับความสำคัญ',
      PMDT07_ASSIGNEE_LABEL: 'ผู้รับผิดชอบ',
      PMDT07_ASSIGNEE_PLACEHOLDER: 'เลือกผู้รับผิดชอบ',
      PMDT07_ESTIMATED_MANDAY_LABEL: 'Estimated Manday',
      PMDT07_ESTIMATED_MANDAY_PLACEHOLDER: 'ระบุ Manday',
      PMDT07_DESC_LABEL: 'รายละเอียด Specification',
      PMDT07_DESC_PLACEHOLDER: 'พิมพ์รายละเอียดที่นี่...',
      PMDT07_ATTACHMENTS_LABEL: 'เอกสารแนบ',
      PMDT07_ATTACHMENTS_HELPER: 'ลากไฟล์มาวาง หรือ คลิกเพื่ออัปโหลด',
      PMDT07_CREATE_SPEC_TITLE: 'สร้าง Specification',
      PMDT07_EDIT_SPEC_TITLE: 'แก้ไข Specification',
      PMDT07_VIEW_SPEC_TITLE: 'รายละเอียด Specification',
      PMDT07_CANCEL_BTN: 'ยกเลิก',
      PMDT07_SAVE_BTN: 'บันทึก',
      PMDT07_SUBMIT_BTN: 'ส่งขออนุมัติ',
      PMDT07_HEADER_TITLE: 'รายการ Specification',
      PMDT01_CREATE_PHASE_TITLE: 'สร้าง Phase',
      PMDT01_EDIT_PHASE_TITLE: 'แก้ไข Phase',
      PMDT01_EMPTY_TITLE: 'ยังไม่มี Phase ในโครงการนี้',
      PMDT01_EMPTY_HINT: 'เริ่มต้นด้วยการคลิกปุ่ม "+ เพิ่ม Phase" ด้านบนเพื่อวางแผนงานและไมล์สโตน',
      PMDT01_CUSTOMER_LABEL: 'ลูกค้า',
      PMDT01_CUSTOMER_PLACEHOLDER: 'ค้นหาและเลือกลูกค้า',
      PMDT01_PROJECT_LABEL: 'โครงการ',
      PMDT01_PROJECT_PLACEHOLDER: 'ค้นหาและเลือกโครงการ',
      PMDT02_CREATE_MS_TITLE_H: 'สร้าง Milestone',
      PMDT02_EDIT_MS_TITLE_H: 'แก้ไข Milestone',
      PMDT02_PHASE_LABEL: 'เฟส (Phase)',
      PMDT02_SELECT_PHASE_PLACEHOLDER: 'ค้นหาและเลือกเฟส',
      PMDT02_CREATE_WP_TITLE_H: 'สร้าง Work Package',
      PMDT02_EDIT_WP_TITLE_H: 'แก้ไข Work Package',
      PMDT02_MILESTONE_LABEL: 'ไมล์สโตน (Milestone)',
      PMDT02_SELECT_MILESTONE_PLACEHOLDER: 'ค้นหาและเลือกไมล์สโตน',
      PMDT02_CREATE_TASK_TITLE_H: 'สร้าง Task',
      PMDT02_EDIT_TASK_TITLE_H: 'แก้ไข Task',
      PMDT02_WORK_PACKAGE_LABEL: 'แพ็กเกจงาน (Work Package)',
      PMDT02_SELECT_WP_PLACEHOLDER: 'ค้นหาและเลือกแพ็กเกจงาน',
      PMDT06_CUSTOMER_LABEL: 'ลูกค้า',
      PMDT06_CUSTOMER_PLACEHOLDER: 'ค้นหาและเลือกลูกค้า',
      PMDT06_PROJECT_LABEL: 'โครงการ',
      PMDT06_UPSTREAM_CONTEXT_LABEL: 'ผลกระทบระดับโครงการและลูกค้า (Upstream Impact)',
      PMDT06_IMPACT_CUSTOMERS_LABEL: 'ลูกค้าที่ได้รับผลกระทบ',
      PMDT06_IMPACT_PROJECTS_LABEL: 'โครงการที่ได้รับผลกระทบ',
      PMDT06_IMPACT_REQUIREMENT: 'ความต้องการ (Requirement)',
      PMDT06_IMPACT_SPECIFICATION: 'ข้อกำหนด (Specification)',
      PMDT06_IMPACT_DIAGRAM: 'แผนภาพ (Diagram)',
      PMDT06_IMPACT_TASK: 'งาน (Task)',
      PMDT06_IMPACT_TESTCASE: 'ชุดทดสอบ (Test Case)',
      PMDT06_IMPACT_TESTPLAN: 'แผนทดสอบ (Test Plan)',
      PMDT06_IMPACT_BUG: 'ข้อผิดพลาด (Bug)',
      PMDT06_IMPACT_CONTRACT: 'สัญญาโครงการ',
      PMDT06_IMPACT_DESIGNREVIEW: 'ผลตรวจทานการออกแบบ',
      PMDT06_IMPACT_DELIVERY: 'การส่งมอบงาน',
      PMDT06_IMPACT_USERMANUAL: 'คู่มือการใช้งาน',
      PMDT06_IMPACT_INVOICE: 'ใบแจ้งหนี้/การชำระเงิน',
      PMDT06_IMPACT_MATICKET: 'แจ้งซ่อม MA',
      PMDT06_IMPACT_MARENEWAL: 'ต่ออายุ MA',
      PMDT12_SEARCH_PLACEHOLDER: 'ค้นหา Scenario, รหัสเคส, หัวข้อ, ผู้ทดสอบ...',
      PMDT12_FILTER_STATUS_PH: '📊 ทุกสถานะ Test Case',
      PMDT12_FILTER_PRIORITY_PH: '⚡ ทุกระดับความสำคัญ',
      PMDT12_FILTER_TASK_STATUS_PH: '🎯 ทุกสถานะ Task',
      PMDT12_SEVERITY_LABEL: 'ระดับความรุนแรง',
      PMDT12_SEVERITY_PH: 'เลือกระดับความรุนแรง',
      PMDT12_BUG_TITLE_LABEL: 'ชื่อ / หัวข้อ Bug',
      PMDT12_BUG_TITLE_PH: 'ระบุข้อผิดพลาดที่พบ...',
      PMDT12_ASSIGNED_TO_LABEL: 'ผู้รับผิดชอบแก้ไข',
      PMDT12_ASSIGNED_TO_PH: 'เลือกสมาชิกทีมผู้รับผิดชอบ',
      PMDT12_MANDAY_LABEL: 'ประมาณการ Manday',
      PMDT12B_TASK_TRACE_LABEL: 'Task',
      PMDT12B_TASK_TRACE_PLACEHOLDER: 'เลือก Task',
      PMDT12B_SCENARIO_CODE_LABEL: 'รหัส Test Scenario',
      PMDT12B_SCENARIO_CODE_PLACEHOLDER: 'เช่น SC-001, SC-LOGIN',
      PMDT12B_SCENARIO_NAME_LABEL: 'ชื่อ Test Scenario',
      PMDT12B_SCENARIO_NAME_PLACEHOLDER: 'เช่น การเข้าสู่ระบบ, การพิมพ์รายงาน...',
      PMDT12B_TEST_TYPE_LABEL: 'ประเภทการทดสอบ',
      PMDT12B_TEST_TYPE_PLACEHOLDER: 'เลือกประเภทการทดสอบ',
      PMDT12B_PRIORITY_LABEL: 'ความสำคัญ',
      PMDT12B_PRIORITY_PLACEHOLDER: 'เลือกระดับความสำคัญ',
      PMDT12B_DESCRIPTION_LABEL: 'คำอธิบาย / วัตถุประสงค์ของ Scenario',
      PMDT12B_DESCRIPTION_PLACEHOLDER: 'อธิบายขอบเขตและวัตถุประสงค์ในการทดสอบกลุ่มนี้...',
      PMDT12B_RICH_TEXT_HINT: 'รองรับการจัดรูปแบบข้อความ',
      PMDT12B_STATUS_ACTIVE_LABEL: 'เปิดใช้งาน',
      AIWIZARD_HEADING: 'AI Full-Project Generator',
      AIWIZARD_SUBHEADING: 'สร้างโครงสร้างโปรเจกต์และโมดูลเชื่อมโยงครบวงจรด้วย AI ภายในคลิกเดียว',
      AIWIZARD_HISTORY_TITLE: 'ประวัติการสร้างโครงการด้วย AI',
      AIWIZARD_HISTORY_EMPTY: 'ยังไม่มีประวัติการสร้างโครงการ',
      AIWIZARD_HISTORY_LOADING: 'กำลังโหลดประวัติ...',
      AIWIZARD_FAILED_MODULES_TITLE: 'โมดูลที่ไม่ถูกสร้าง',
      AIWIZARD_SKIPPED_STEP_MSG: 'ถูกข้ามเนื่องจากขั้นตอนก่อนหน้าไม่สำเร็จ',
      AIWIZARD_STEP1_LABEL: '1. บรีฟโครงการ',
      AIWIZARD_STEP2_LABEL: '2. ตรวจสอบโครงสร้าง',
      AIWIZARD_STEP3_LABEL: '3. สร้างข้อมูลทั้งหมด',
      AIWIZARD_STEP4_LABEL: '4. เริ่มรีวิวโครงการ',
      AIWIZARD_PROJECT_NAME_LABEL: 'ชื่อโครงการ (ถ้ามี)',
      AIWIZARD_BRIEF_LABEL: 'รายละเอียด / ความต้องการโครงการ (บรีฟงาน)',
      AIWIZARD_DURATION_LABEL: 'ระยะเวลาโครงการโดยประมาณ (สัปดาห์)',
      AIWIZARD_MODEL_LABEL: 'AI Engine Model',
      AIWIZARD_TOR_LABEL: 'เอกสาร TOR หรือไฟล์แนบอ้างอิง',
      AIWIZARD_MODULE_CONTRACT: 'สัญญา (Contract)',
      AIWIZARD_MODULE_TEST: 'Test Scenario & Test Case',
      AIWIZARD_MODULE_MANUAL: 'คู่มือการใช้งาน (User Manual)',
      AIWIZARD_MODULE_INVOICE: 'ใบแจ้งหนี้ร่างจากงวดส่งมอบ',
      AIWIZARD_MODULE_DIAGRAM: 'Diagram (DFD / ER / Flowchart / Use Case)',
      AIWIZARD_MODULE_DESIGN_REVIEW: 'Design Review',
      AIWIZARD_MODULE_MA: 'MA Ticket & ข้อเสนอต่ออายุ MA',
      AIWIZARD_SAMPLE_REQUIREMENTS: 'รายการ Requirements ตัวอย่าง',
      AIWIZARD_SAMPLE_SPECIFICATIONS: 'รายการ Specifications ตัวอย่าง',
      AIWIZARD_GENERATING_TITLE: 'AI กำลังสร้างโครงการและโมดูลตามลำดับ SDLC...',
      AIWIZARD_GENERATING_DESC: 'งานทำงานเบื้องหลัง ใช้เวลาประมาณ 2-5 นาที กรุณารอจนเสร็จ',
      AIWIZARD_SUCCESS_TITLE: 'สร้างโครงการสมบูรณ์เรียบร้อย!',
      AIWIZARD_DRAFT_BADGE: 'Draft (รอรีวิว)',
      AIWIZARD_STARTING: 'กำลังเริ่มต้น...',
      AIWIZARD_CREATING_LABEL: 'กำลังสร้าง: {{label}}',
      AIWIZARD_PROGRESS_DONE: 'เสร็จแล้ว {{done}}/{{total}} ขั้นตอน',
      AIWIZARD_PROGRESS_FAILED_SUFFIX: ' (พลาด {{failed}})',
      AIWIZARD_COUNT_PROJECT: 'โครงการ',
      AIWIZARD_COUNT_CONTRACT: 'สัญญา',
      AIWIZARD_COUNT_WBS: 'เฟส / ไมล์สโตน / แพ็กเกจงาน',
      AIWIZARD_COUNT_REQUIREMENT: 'ความต้องการ',
      AIWIZARD_COUNT_SPECIFICATION: 'สเปกระบบ',
      AIWIZARD_COUNT_TASK: 'งาน (Task)',
      AIWIZARD_COUNT_TEST: 'เทสต์ซีนาริโอ / เทสต์เคส',
      AIWIZARD_COUNT_DELIVERY: 'งวดส่งมอบ',
      AIWIZARD_COUNT_MANUAL: 'คู่มือ',
      AIWIZARD_COUNT_INVOICE: 'ใบแจ้งหนี้ร่าง',
      AIWIZARD_COUNT_DIAGRAM: 'ไดอะแกรม',
      AIWIZARD_COUNT_DESIGN_REVIEW: 'Design Review',
      AIWIZARD_COUNT_MA: 'MA Ticket / ต่ออายุ',
      AIWIZARD_STATUS_RUNNING: 'กำลังทำงาน',
      AIWIZARD_STATUS_COMPLETED: 'สำเร็จทั้งหมด',
      AIWIZARD_STATUS_COMPLETED_WITH_ERRORS: 'สำเร็จบางส่วน',
      AIWIZARD_STATUS_FAILED: 'ไม่สำเร็จ',
      AIWIZARD_ERROR_TITLE: 'ข้อผิดพลาด',
      AIWIZARD_TRY_AGAIN: 'โปรดลองใหม่',
      AIWIZARD_ANALYZE_ERROR_MSG: 'เกิดข้อผิดพลาดในการวิเคราะห์โครงการ: {{msg}}',
      AIWIZARD_ATTACHMENT_ERROR_MSG: 'เกิดข้อผิดพลาดในการประมวลผลไฟล์แนบ',
      AIWIZARD_START_PIPELINE_ERROR_MSG: 'เกิดข้อผิดพลาดในการเริ่มสร้างโครงการ: {{msg}}',
      AIWIZARD_CREATE_PROJECT_FAILED_MSG: 'สร้างโครงการไม่สำเร็จ',
      AIWIZARD_PARTIAL_SUCCESS_TITLE: 'สร้างเสร็จบางส่วน',
      AIWIZARD_SOME_STEPS_FAILED_MSG: 'บางขั้นตอนไม่สำเร็จ',
      AIWIZARD_POLL_ERROR_MSG: 'ไม่สามารถติดตามความคืบหน้าได้ (งานอาจยังทำงานอยู่เบื้องหลัง ตรวจสอบรายการโครงการอีกครั้ง)',
      AIWIZARD_LOAD_HISTORY_ERROR_MSG: 'ไม่สามารถโหลดประวัติการสร้างโครงการได้',
      AIWIZARD_BTN_HISTORY: 'ประวัติ',
      AIWIZARD_BTN_HISTORY_TITLE: 'ประวัติการสร้างโครงการ',
      AIWIZARD_CLOSE_BTN: 'ปิด',
      AIWIZARD_NO_PROJECT_NAME: '(ไม่มีชื่อโครงการ)',
      AIWIZARD_PAGE_INFO: 'หน้า {{page}} / {{total}}',
      AIWIZARD_UNIT_WEEKS: 'สัปดาห์',
      AIWIZARD_GO_TO_PROJECT_BTN: 'ไปที่โครงการนี้',
      AIWIZARD_ANALYZING_BANNER: 'AI กำลังวิเคราะห์บรีฟและวางโครงสร้างโครงการ กรุณารอสักครู่...',
      AIWIZARD_PROJECT_NAME_PLACEHOLDER: 'เช่น โครงการพัฒนาระบบคลังสินค้าและจัดส่งอัจฉริยะ',
      AIWIZARD_BRIEF_PLACEHOLDER: 'อธิบายฟังก์ชันที่ต้องการ กลุ่มผู้ใช้งาน เป้าหมายทางธุรกิจ หรือขอบเขตงานที่ต้องการให้ AI ช่วยวางโครงสร้าง...',
      AIWIZARD_CUSTOMER_LABEL: 'ลูกค้า (Customer)',
      AIWIZARD_CUSTOMER_HINT: 'เลือกจากระบบ หรือปล่อยว่างให้ AI ตรวจจับ/สร้างให้อัตโนมัติ',
      AIWIZARD_CUSTOMER_AUTO_OPTION: '-- อัตโนมัติ (AI Smart Match / สร้างใหม่อัตโนมัติ) --',
      AIWIZARD_ATTACH_TOR_BTN: 'แนบไฟล์ TOR / เอกสารบรีฟ',
      AIWIZARD_ESTIMATED_DURATION: 'ระยะเวลาโครงการ: {{weeks}} สัปดาห์',
      AIWIZARD_SELECT_MODULES_LABEL: 'เลือกโมดูลที่ต้องการให้ AI สร้างอัตโนมัติ:',
      AIWIZARD_MODULE_REQUIREMENTS_COUNT: 'Requirements ({{count}} รายการ)',
      AIWIZARD_MODULE_SPECS_COUNT: 'System Specifications ({{count}} รายการ)',
      AIWIZARD_MODULE_TASKS_COUNT: 'WBS / Tasks Breakdown ({{count}} รายการ)',
      AIWIZARD_MODULE_GANTT_COUNT: 'Gantt Phases & Timeline ({{count}} เฟส)',
      AIWIZARD_MODULE_DELIVERY_COUNT: 'Delivery Milestones ({{count}} งวด)',
      AIWIZARD_SUCCESS_DESC_PREFIX: 'ข้อมูลทั้งหมดถูกบันทึกในสถานะ',
      AIWIZARD_SUCCESS_DESC_SUFFIX: 'พร้อมผูกความสัมพันธ์ Traceability ทุกโมดูล',
      AIWIZARD_CANCEL_BTN: 'ยกเลิก',
      AIWIZARD_ANALYZING_BTN: 'AI กำลังวิเคราะห์บรีฟ...',
      AIWIZARD_PREVIEW_BTN: 'วิเคราะห์และดูโครงสร้าง (Preview Plan)',
      AIWIZARD_ADJUST_BRIEF_BTN: 'ปรับบรีฟ',
      AIWIZARD_CONFIRM_CREATE_BTN: 'ยืนยันสร้างโปรเจกต์ทั้งหมดทันที',
      AIWIZARD_VIEW_GANTT_BTN: 'ดูใน Gantt Chart',
      AIWIZARD_REVIEW_PROJECT_BTN: 'เปิดรีวิวโปรเจกต์นี้',
      AIWIZARD_STEP_CUSTOMER: 'ลูกค้า (Customer)',
      AIWIZARD_STEP_PROJECT: 'สร้างโครงการ',
      AIWIZARD_STEP_CONTRACT: 'สัญญา (Contract)',
      AIWIZARD_STEP_WBS: 'Phase / Milestone / Work Package',
      AIWIZARD_STEP_REQUIREMENT: 'Requirement',
      AIWIZARD_STEP_DIAGRAM: 'Diagram (DFD / ER / Flowchart / Use Case)',
      AIWIZARD_STEP_SPECIFICATION: 'Specification',
      AIWIZARD_STEP_DESIGN_REVIEW: 'Design Review',
      AIWIZARD_STEP_TASK: 'Task',
      AIWIZARD_STEP_TEST: 'Test Scenario / Test Case',
      AIWIZARD_STEP_DELIVERY: 'การส่งมอบ (Delivery)',
      AIWIZARD_STEP_MANUAL: 'คู่มือการใช้งาน',
      AIWIZARD_STEP_INVOICE: 'ใบแจ้งหนี้ (ร่าง)',
      AIWIZARD_STEP_MA: 'MA Ticket / ต่ออายุ MA',

      BURT03_ADD_NODE_TITLE: 'เพิ่มบทบาท',
      BURT03_EDIT_NODE_TITLE: 'แก้ไขบทบาท',
      BURT03_ROLE_CODE: 'รหัสบทบาท',
      BURT03_NAME_EN: 'ชื่อบทบาท (อังกฤษ)',
      BURT03_NAME_LOCAL: 'ชื่อบทบาท (ไทย)',
      BURT03_COLOR: 'สีสัญลักษณ์',
      BURT03_EDIT_ROLE: 'แก้ไขบทบาท',
      BURT03_ADD_SUB_ROLE: 'เพิ่มบทบาทย่อย',
      BURT03_REMOVE_ROLE: 'ลบบทบาท',
      COMMON_SAVE_BTN: 'บันทึก',

      PMDT05_ACTIVE_BADGE: 'พร้อมใช้งาน',
      PMDT05_AI_ASSISTANT_TITLE: 'ผู้ช่วย AI Diagram',
      PMDT05_AI_CONNECT_ERROR_MSG: 'ไม่สามารถเชื่อมต่อกับ AI ได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง',
      PMDT05_AI_DIAGRAM_ASSISTANT: 'ผู้ช่วย AI สร้าง Diagram',
      PMDT05_AI_MODEL_LABEL: 'โมเดล AI',
      PMDT05_AI_MODEL_PLACEHOLDER: 'เลือกโมเดล AI',
      PMDT05_AI_PROCESSING_LABEL: 'AI กำลังประมวลผล...',
      PMDT05_AI_WELCOME_DESC: 'ผู้ช่วยอัจฉริยะสำหรับสร้างและปรับแต่งไดอะแกรม DFD, ER, Flowchart และวิเคราะห์สถาปัตยกรรมระบบ',
      PMDT05_ALL_PROJECTS: 'ทุกโครงการ (ทั้งหมด)',
      PMDT05_APPROVAL_PROCESS_LABEL: 'ขั้นตอนการขออนุมัติ',
      PMDT05_APPROVED_BADGE: 'อนุมัติแล้ว',
      PMDT05_APPROVED_LABEL: 'อนุมัติแล้ว',
      PMDT05_APPROVED_TITLE: 'เอกสารได้รับการอนุมัติแล้ว',
      PMDT05_AUTO_MIGRATION_MODE: 'สร้าง Migration Script v{0}',
      PMDT05_AUTO_SAVED: 'บันทึกอัตโนมัติเรียบร้อย',
      PMDT05_BACK_LABEL: 'ย้อนกลับ',
      PMDT05_BACK_TO_CHAT_TITLE: 'กลับไปหน้าสนทนา',
      PMDT05_BY_PREFIX: 'โดย: ',
      PMDT05_CANCEL_BTN: 'ยกเลิก',
      PMDT05_CHAT_BTN: 'ผู้ช่วย AI',
      PMDT05_CHAT_HISTORY_LABEL: 'ประวัติการสนทนา',
      PMDT05_CHAT_INPUT_PLACEHOLDER: 'พิมพ์คำสั่งหรือขอคำแนะนำจาก AI...',
      PMDT05_CHAT_TITLE: 'ผู้ช่วย AI',
      PMDT05_CLEAR_CHAT_TITLE: 'ล้างบทสนทนา',
      PMDT05_CLOSE_BTN: 'ปิด',
      PMDT05_CLOSE_CHAT_TITLE: 'ปิดหน้าต่างแชท',
      PMDT05_CONNECTING: 'กำลังเชื่อมต่อ...',
      PMDT05_COPIED_LABEL: 'คัดลอกแล้ว',
      PMDT05_COPIED_TEXT: 'คัดลอกแล้ว',
      PMDT05_COPY_MERMAID_LABEL: 'คัดลอก Mermaid',
      PMDT05_COPY_MERMAID_TITLE: 'คัดลอกโค้ด Mermaid',
      PMDT05_COPY_TEXT: 'คัดลอก',
      PMDT05_CREATE_DIAGRAM_TITLE: 'สร้าง Diagram ใหม่',
      PMDT05_CREATE_DIALOG_BTN: 'สร้างไดอะแกรม',
      PMDT05_CREATE_FAIL_TITLE: 'สร้างไดอะแกรมไม่สำเร็จ',
      PMDT05_CREATE_NEW_CHAT_LABEL: 'เริ่มแชทใหม่',
      PMDT05_CREATE_SUCCESS_MSG: 'สร้างไดอะแกรม {0} สำเร็จแล้ว',
      PMDT05_CREATE_SUCCESS_TITLE: 'สร้างไดอะแกรมสำเร็จ',
      PMDT05_DB_VENDOR_LABEL: 'ประเภทฐานข้อมูล ',
      PMDT05_DEFAULT_SESSION_TITLE: 'บทสนทนาทั่วไป',
      PMDT05_DELETE_SESSION_TITLE: 'ลบประวัติการสนทนา',
      PMDT05_DELETE_TAB_CONFIRM_MSG: 'คุณต้องการลบไดอะแกรม \'{0}\' ใช่หรือไม่? การกระทำนี้ไม่สามารถย้อนกลับได้',
      PMDT05_DELETE_TAB_CONFIRM_TITLE: 'ยืนยันการลบไดอะแกรม',
      PMDT05_DELETE_TAB_FAIL_MSG: 'เกิดข้อผิดพลาดในการลบไดอะแกรม',
      PMDT05_DELETE_TAB_TITLE: 'ลบแท็บไดอะแกรม',
      PMDT05_DELETED_TITLE: 'ลบสำเร็จ',
      PMDT05_DIAGRAM_CODE_LABEL: 'รหัสไดอะแกรม',
      PMDT05_DIAGRAM_CODE_PLACEHOLDER: 'เช่น DIAG-001 (เว้นว่างเพื่อสร้างอัตโนมัติ)',
      PMDT05_DIAGRAM_COUNT: 'แผนภาพ',
      PMDT05_DIAGRAM_NAME_LABEL: 'ชื่อไดอะแกรม',
      PMDT05_DIAGRAM_NAME_PLACEHOLDER: 'ระบุชื่อไดอะแกรม เช่น Flow การสั่งซื้อสินค้า',
      PMDT05_DIAGRAM_TYPE_LABEL: 'ประเภทไดอะแกรม',
      PMDT05_DIAGRAM_TYPE_PLACEHOLDER: 'เลือกประเภทไดอะแกรม',
      PMDT05_DOWNLOAD_BTN: 'ดาวน์โหลด',
      PMDT05_DOWNLOAD_SQL_BTN: 'ดาวน์โหลดไฟล์ SQL',
      PMDT05_DRAFT_BADGE: 'แบบร่าง',
      PMDT05_DRAFT_TITLE: 'แบบร่าง',
      PMDT05_DRAW_ER_FIRST_MSG: 'กรุณาวาดแผนภาพ ER ก่อนสร้างคำสั่ง SQL',
      PMDT05_DRAWIO_READY: 'พร้อมใช้งาน',
      PMDT05_EDIT_DIAGRAM_TITLE: 'แก้ไขข้อมูลไดอะแกรม',
      PMDT05_EDIT_NAME_TITLE: 'เปลี่ยนชื่อหรือแก้ไขข้อมูล',
      PMDT05_EDIT_SESSION_TITLE: 'แก้ไขชื่อเซสชัน',
      PMDT05_EDIT_TAB_TITLE: 'แก้ไขไดอะแกรม',
      PMDT05_EMPTY_DIAGRAM_MSG: 'ไม่พบเนื้อหาในไดอะแกรม',
      PMDT05_EMPTY_DIAGRAM_TITLE: 'ไดอะแกรมว่างเปล่า',
      PMDT05_ERROR_GENERIC_TITLE: 'เกิดข้อผิดพลาด',
      PMDT05_ERROR_TITLE: 'ข้อผิดพลาด',
      PMDT05_FAILED_TITLE: 'ดำเนินการไม่สำเร็จ',
      PMDT05_GEN_FAILED_TITLE: 'สร้าง SQL ไม่สำเร็จ',
      PMDT05_GEN_SQL_FAIL_MSG: 'เกิดข้อผิดพลาดในการสร้างคำสั่ง SQL',
      PMDT05_GENERATE_SQL_BTN: 'สร้างคำสั่ง SQL',
      PMDT05_GEN_MODE_LABEL: 'โหมดการสร้างคำสั่ง SQL',
      PMDT05_FULL_REGEN_MODE: 'สร้างโครงสร้างใหม่ทั้งหมด (Full Schema)',
      PMDT05_FULL_REGEN_DESC: 'สร้างคำสั่ง CREATE TABLE และ Constraints ทั้งหมดในทีเดียว (เหมาะสำหรับขึ้นระบบใหม่)',
      PMDT05_FULL_REGEN_BADGE: 'สร้างทุกตารางใหม่ทั้งหมด',
      PMDT05_GENERATE_SQL_TITLE: 'สร้างคำสั่ง SQL จาก ER Diagram',
      PMDT05_GENERATED_SQL_RESULT: 'ผลลัพธ์คำสั่ง SQL',
      PMDT05_GENERATING_TEXT: 'กำลังสร้าง...',
      PMDT05_GENERIC_ERROR: 'เกิดข้อผิดพลาดในระบบ',
      PMDT05_GET_XML_FAIL_MSG: 'ไม่สามารถดึงข้อมูล XML จากหน้าจอวาดได้',
      PMDT05_HIDE_SQL_SCRIPT: 'ซ่อนสคริปต์ SQL',
      PMDT05_HISTORY_LABEL: 'ประวัติ',
      PMDT05_HISTORY_LOG_TAB: 'ประวัติการสร้าง (History Log)',
      PMDT05_INITIAL_SETUP_DESC: 'สร้างตารางใหม่ทั้งหมดพร้อม Foreign Key และ Indexes',
      PMDT05_INITIAL_SETUP_MODE: 'สร้างฐานข้อมูลใหม่เริ่มต้น (Initial Setup)',
      PMDT05_INSERT_MERMAID_FAIL_MSG: 'ไม่สามารถแทรกแผนภาพลงในหน้าจอวาดได้',
      PMDT05_INSERT_MERMAID_FAIL_TITLE: 'แทรกแผนภาพไม่สำเร็จ',
      PMDT05_INSERT_MERMAID_LABEL: 'แทรกลงใน Diagram',
      PMDT05_INSERT_MERMAID_SUCCESS_MSG: 'แทรกแผนภาพลงในหน้าจอวาดเรียบร้อยแล้ว',
      PMDT05_INSERT_MERMAID_SUCCESS_TITLE: 'แทรกแผนภาพสำเร็จ',
      PMDT05_INSERT_MERMAID_TITLE: 'แทรกโค้ด Mermaid ลงบนหน้าวาด Draw.io',
      PMDT05_LOAD_FAIL_TITLE: 'โหลดไดอะแกรมไม่สำเร็จ',
      PMDT05_LOADING_DIAGRAM: 'กำลังโหลดไดอะแกรม...',
      PMDT05_LOADING_HISTORY_LOG: 'กำลังโหลดประวัติการสร้าง...',
      PMDT05_LOADING_TABS: 'กำลังโหลดข้อมูลแท็บ...',
      PMDT05_LOCKED_DELETE_MSG: 'ไดอะแกรมนี้ได้รับการอนุมัติแล้ว ไม่สามารถลบได้',
      PMDT05_LOCKED_MSG: 'ไดอะแกรมนี้ได้รับการอนุมัติแล้ว ไม่สามารถแก้ไขได้',
      PMDT05_LOCKED_SAVE_MSG: 'ไม่สามารถบันทึกได้ เนื่องจากเอกสารผ่านการอนุมัติแล้ว',
      PMDT05_LOCKED_TITLE: 'เอกสารถูกล็อก',
      PMDT05_MESSAGES_COUNT_SUFFIX: 'ข้อความ',
      PMDT05_MIGRATION_BASED_ON: 'เปรียบเทียบความแตกต่างจากเวอร์ชัน {0}',
      PMDT05_MIGRATION_MODE_DESC: 'สร้างคำสั่ง ALTER TABLE / ADD COLUMN เพื่อปรับปรุงฐานข้อมูลโดยไม่ลบข้อมูลเดิม',
      PMDT05_MISSING_REQ_MSG: 'กรุณาระบุข้อมูลที่จำเป็นให้ครบถ้วน',
      PMDT05_MISSING_REQ_TITLE: 'ข้อมูลไม่ครบถ้วน',
      PMDT05_NEEDS_REVISION_BADGE: 'ต้องแก้ไข',
      PMDT05_NEW_CHAT_LABEL: 'แชทใหม่',
      PMDT05_NEW_DIAGRAM_BTN: '+ สร้าง Diagram ใหม่',
      PMDT05_NEW_SESSION_TITLE: 'สร้างการสนทนาใหม่',
      PMDT05_NEW_SESSION_TITLE_DEFAULT: 'การสนทนาใหม่',
      PMDT05_NO_CHAT_HISTORY_MSG: 'ยังไม่มีประวัติการสนทนา',
      PMDT05_NO_DIAGRAM_SAVE_MSG: 'กรุณาเปิดหรือสร้างไดอะแกรมก่อนบันทึก',
      PMDT05_NO_DIAGRAM_TITLE: 'ไม่พบไดอะแกรม',
      PMDT05_NO_ER_PAGE_MSG: 'กรุณาเลือกหน้า ER Diagram ก่อนสร้าง SQL',
      PMDT05_NO_HISTORY_FOUND: 'ไม่พบประวัติการสนทนาที่ค้นหา',
      PMDT05_NO_HISTORY_MSG: 'ยังไม่มีประวัติการสร้าง SQL สำหรับไดอะแกรมนี้',
      PMDT05_NO_MESSAGES_MSG: 'ยังไม่มีข้อความในการสนทนานี้',
      PMDT05_NO_PAGE_SELECTED_TITLE: 'ยังไม่ได้เลือกหน้า',
      PMDT05_NO_PROJECT_DESC: 'กรุณาสร้างหรือเลือกโครงการก่อนสร้างไดอะแกรม',
      PMDT05_NO_PROJECT_ID_MSG: 'ไม่พบรหัสโครงการ กรุณาเลือกโครงการก่อนดำเนินการ',
      PMDT05_NO_PROJECT_TITLE: 'ยังไม่ได้เลือกโครงการ',
      PMDT05_NO_SEARCH_RESULT: 'ไม่พบผลลัพธ์การค้นหา',
      PMDT05_OPEN_DIAGRAM_FIRST_MSG: 'กรุณาเปิดไดอะแกรมที่ต้องการก่อนดำเนินการ',
      PMDT05_PAGE_NOT_EXIST_MSG: 'หน้าที่เลือกไม่มีอยู่ในระบบ',
      PMDT05_PAGE_NOT_FOUND_TITLE: 'ไม่พบหน้าที่ระบุ',
      PMDT05_PENDING_BADGE: 'รออนุมัติ',
      PMDT05_PENDING_TITLE: 'อยู่ระหว่างรอการอนุมัติ',
      PMDT05_PRESS_ENTER_PREFIX: 'กด ',
      PMDT05_PRESS_ENTER_SUFFIX: ' เพื่อส่งข้อความ',
      PMDT05_PREVIEW_SQL_SCRIPT: 'ดูสคริปต์ SQL',
      PMDT05_PROJECTS_SELECTED: 'โครงการที่เลือก',
      PMDT05_PROMPT_ANALYZE_TEXT: 'ช่วยวิเคราะห์สถาปัตยกรรมระบบและความสัมพันธ์ของข้อมูลในไดอะแกรมนี้',
      PMDT05_PROMPT_ANALYZE_TITLE: 'วิเคราะห์สถาปัตยกรรม',
      PMDT05_PROMPT_ER_TEXT: 'ช่วยออกแบบ ER Diagram สำหรับระบบจัดการคำสั่งซื้อและสต็อกสินค้า',
      PMDT05_PROMPT_ER_TITLE: 'ออกแบบ ER Diagram',
      PMDT05_PROMPT_FLOWCHART_TEXT: 'ช่วยวาด Flowchart แสดงขั้นตอนการชำระเงินและตรวจสอบสิทธิ์ผู้ใช้',
      PMDT05_PROMPT_FLOWCHART_TITLE: 'วาด Flowchart กระบวนการ',
      PMDT05_PROMPT_SEQUENCE_TEXT: 'ช่วยวาด Sequence Diagram การเรียกใช้งาน API จาก Frontend ผ่าน Gateway ไปยัง Backend',
      PMDT05_PROMPT_SEQUENCE_TITLE: 'ออกแบบ Sequence Diagram',
      PMDT05_REJECTED_BADGE: 'ไม่อนุมัติ',
      PMDT05_REJECTED_TITLE: 'เอกสารถูกปฏิเสธการอนุมัติ',
      PMDT05_RELOAD_BTN: 'โหลดใหม่',
      PMDT05_RELOAD_TITLE: 'โหลดไดอะแกรมใหม่จากเซิร์ฟเวอร์',
      PMDT05_REQ_SOURCE_LABEL: 'ความต้องการอ้างอิง (Requirement)',
      PMDT05_REQUEST_CHANGE_BTN: 'ขอแก้ไข (Change Request)',
      PMDT05_REQUIREMENT_LABEL: 'ผูกกับ Requirement (ถ้ามี)',
      PMDT05_REQUIREMENT_PLACEHOLDER: 'เลือก Requirement...',
      PMDT05_SAVE_BTN: 'บันทึก',
      PMDT05_SAVE_DIALOG_BTN: 'บันทึกข้อมูล',
      PMDT05_SAVE_FAIL_TITLE: 'บันทึกไม่สำเร็จ',
      PMDT05_SAVE_FAILED_STATUS: 'บันทึกไม่สำเร็จ',
      PMDT05_SAVE_LABEL: 'บันทึก',
      PMDT05_SAVE_SUCCESS_MSG: 'บันทึกข้อมูลไดอะแกรมเรียบร้อยแล้ว',
      PMDT05_SAVE_SUCCESS_TITLE: 'บันทึกสำเร็จ',
      PMDT05_SAVE_TITLE: 'บันทึกไดอะแกรม',
      PMDT05_SAVE_TITLE_NAME: 'บันทึกไดอะแกรม',
      PMDT05_SAVED_MANUALLY: 'บันทึกข้อมูลสำเร็จ',
      PMDT05_SAVED_SUFFIX: ' (บันทึกแล้ว)',
      PMDT05_SAVING_MSG: 'ระบบกำลังบันทึกข้อมูล กรุณารอสักครู่',
      PMDT05_SAVING_TITLE: 'กำลังบันทึก',
      PMDT05_SEARCH_HISTORY_PLACEHOLDER: 'ค้นหาบทสนทนา...',
      PMDT05_SELECT_APPROVAL_FLOW_LABEL: 'ส่งขออนุมัติตามขั้นตอน',
      PMDT05_SELECT_APPROVAL_FLOW_PLACEHOLDER: 'เลือกขั้นตอนการอนุมัติ...',
      PMDT05_SELECT_ER_PAGE_LABEL: 'เลือกหน้า ER Diagram',
      PMDT05_SELECT_PAGE_MSG: 'กรุณาเลือกหน้าไดอะแกรมที่ต้องการแปลงเป็น SQL',
      PMDT05_SEND_BTN: 'ส่ง',
      PMDT05_SQL_GEN_TITLE: 'สร้างคำสั่ง SQL จาก ER Diagram',
      PMDT05_START_FIRST_GEN_BTN: 'เริ่มสร้าง SQL ครั้งแรก',
      PMDT05_START_NEW_CHAT_BTN: 'เริ่มแชทใหม่',
      PMDT05_SUBMIT_APPROVAL_COMMENT: 'ส่งขออนุมัติ Diagram จากหน้าจอออกแบบ',
      PMDT05_SUBMIT_ON_SAVE_HINT: 'เมื่อเลือกขั้นตอนการอนุมัติ ไดอะแกรมจะถูกส่งเข้าสู่ระบบอนุมัติโดยอัตโนมัติ',
      PMDT05_SUGGESTED_PROMPTS_LABEL: 'ตัวอย่างคำถามหรือคำสั่งที่แนะนำ:',
      PMDT05_TAB_DELETED_MSG: 'ลบไดอะแกรม \'{0}\' เรียบร้อยแล้ว',
      PMDT05_TAB_ID_LABEL: 'รหัสแท็บ:',
      PMDT05_UNKNOWN_PROJECT: 'ไม่ทราบชื่อโครงการ',
      PMDT05_UPDATE_SUCCESS_MSG: 'แก้ไขข้อมูลไดอะแกรม \'{0}\' สำเร็จแล้ว',
      PMDT05_VIEW_ALL_HISTORY_TITLE: 'ดูประวัติการสนทนาทั้งหมด',

      UPLOAD_DROPZONE_EMPTY_TEXT: 'ลากไฟล์มาวางที่นี่ หรือคลิกเพื่อเลือกไฟล์',
      UPLOAD_DROPZONE_HELPER_TEXT: 'รองรับการเลือกไฟล์ได้หลายไฟล์',
      UPLOAD_STATUS_QUEUED: 'รอคิว',
      UPLOAD_STATUS_UPLOADING: 'กำลังอัปโหลด',
      UPLOAD_STATUS_PROCESSING: 'กำลังประมวลผล',
      UPLOAD_STATUS_PAUSED: 'หยุดชั่วคราว',
      UPLOAD_STATUS_FAILED: 'ไม่สำเร็จ',
      UPLOAD_STATUS_STOPPED: 'ยกเลิก',
      UPLOAD_STATUS_COMPLETED: 'เสร็จสมบูรณ์',
      UPLOAD_ACTION_PAUSE: 'หยุดชั่วคราว',
      UPLOAD_ACTION_STOP: 'ยกเลิกอัปโหลด',
      UPLOAD_ACTION_RESUME: 'อัปโหลดต่อ',
      UPLOAD_ACTION_DOWNLOAD: 'ดาวน์โหลดไฟล์',
      UPLOAD_ACTION_REMOVE: 'ลบไฟล์',

      TRACE_REL_RELATED_TO_TARGET: 'เกี่ยวข้องกับ',
      TRACE_REL_RELATED_TO_SOURCE: 'เกี่ยวข้องกับ',
      TRACE_REL_DESIGNED_BY_TARGET: 'ออกแบบจาก',
      TRACE_REL_DESIGNED_BY_SOURCE: 'ออกแบบให้กับ',
      TRACE_REL_IMPLEMENTED_BY_TARGET: 'ถูกพัฒนาโดย',
      TRACE_REL_IMPLEMENTED_BY_SOURCE: 'พัฒนาให้กับ',
      TRACE_REL_DOCUMENTED_BY_TARGET: 'ถูกบันทึกโดย',
      TRACE_REL_DOCUMENTED_BY_SOURCE: 'บันทึกให้กับ',
      TRACE_REL_VERIFIED_BY_TARGET: 'ถูกตรวจสอบโดย',
      TRACE_REL_VERIFIED_BY_SOURCE: 'ตรวจสอบให้กับ',
      TRACE_REL_FAILED_BY_TARGET: 'ล้มเหลวจาก',
      TRACE_REL_FAILED_BY_SOURCE: 'ทำให้ล้มเหลว',
      TRACE_REL_AFFECTED_BY_TARGET: 'ได้รับผลกระทบจาก',
      TRACE_REL_AFFECTED_BY_SOURCE: 'ส่งผลกระทบต่อ',
    },
    en: {
      COMMON_UNSAVED_CHANGES_TITLE: 'Unsaved Changes',
      COMMON_UNSAVED_CHANGES_MSG: 'You have unsaved changes. Leave this page anyway?',
      DASHBOARD_CHIP_ACTIVE_PROJECTS: 'Active Projects',
      DASHBOARD_CHIP_PENDING_APPROVALS: 'Pending Approvals',
      DASHBOARD_CHIP_OPEN_BUGS: 'Open Bugs',
      DASHBOARD_CHIP_EXPIRING_CONTRACTS: 'Expiring Contracts',
      CONTEXT_SWITCHER_TITLE: 'Filter & Switch Project',
      CONTEXT_SWITCHER_POPOVER_TITLE: 'Find & Switch Project',
      CONTEXT_SWITCHER_POPOVER_SUBTITLE: 'Filter and select projects',
      CONTEXT_SWITCHER_SELECT_PROMPT: 'Select project / filter...',
      CONTEXT_SWITCHER_CUSTOMER_SELECTED: 'Customer selected (No project selected)',
      CONTEXT_SWITCHER_SELECTED_PROJECT: 'Selected Project',
      CONTEXT_SWITCHER_PROJECTS_SELECTED: 'projects selected',
      CONTEXT_SWITCHER_SEARCH_PLACEHOLDER: 'Search project name, code...',
      CONTEXT_SWITCHER_CUSTOMER_LABEL: 'Customer',
      CONTEXT_SWITCHER_CUSTOMER_SEARCH_PLACEHOLDER: 'Type to search customer...',
      CONTEXT_SWITCHER_CUSTOMER_NOT_FOUND: 'No customers found',
      CONTEXT_SWITCHER_ALL_CUSTOMERS: 'All Customers',
      CONTEXT_SWITCHER_STATUS_LABEL: 'Status',
      CONTEXT_SWITCHER_PRIORITY_LABEL: 'Priority',
      CONTEXT_SWITCHER_MATCHING_PROJECTS: 'Matching Projects',
      CONTEXT_SWITCHER_LOADING_PROJECTS: 'Loading projects...',
      CONTEXT_SWITCHER_NO_MATCHING_PROJECTS: 'No projects match the filter criteria',
      CONTEXT_SWITCHER_CURRENT: 'Current',
      CONTEXT_SWITCHER_SWITCH: 'Switch',
      CONTEXT_SWITCHER_RESET_FILTERS: 'Reset Filters',
      CONTEXT_SWITCHER_CLEAR_CONTEXT: 'Clear Current Context',
      CONTEXT_SWITCHER_CLOSE: 'Close',
      CONTEXT_SWITCHER_SELECT_ALL: 'Select All',
      CONTEXT_SWITCHER_UNSELECT_ALL: 'Deselect All',
      STATUS_ALL: 'All',
      STATUS_PLANNING: 'Planning',
      STATUS_DEVELOPMENT: 'Development',
      STATUS_UAT: 'UAT',
      STATUS_BUG_FIXING: 'Bug Fixing',
      STATUS_DELIVERED: 'Delivered',
      STATUS_CLOSED: 'Closed',
      PRIORITY_ALL: 'All',
      PRIORITY_CRITICAL: 'Critical',
      PRIORITY_HIGH: 'High',
      PRIORITY_MEDIUM: 'Medium',
      PRIORITY_LOW: 'Low',
      PRIORITY_NORMAL: 'Normal',
      PROJECT_HEALTH_WIDGET_TITLE: 'Project Health',
      PROJECT_HEALTH_STATUS_GOOD: 'Good Health',
      PROJECT_HEALTH_STATUS_WARNING: 'Needs Attention',
      PROJECT_HEALTH_STATUS_CRITICAL: 'Critical',
      PROJECT_HEALTH_TOTAL_SCORE: 'Overall Health Score',
      PROJECT_HEALTH_FACTOR_TASKS: 'Task Progress',
      PROJECT_HEALTH_FACTOR_MANDAY: 'Manday Usage (vs Budget)',
      PROJECT_HEALTH_FACTOR_QUALITY: 'Quality & Bug Fixing',
      PROJECT_HEALTH_FACTOR_PHASE: 'Phase Progress',
      PROJECT_HEALTH_FACTOR_TIMELINE: 'Timeline & Schedule Status',
      PROJECT_HEALTH_DETAIL_NO_TASKS: 'No tasks (0/0)',
      PROJECT_HEALTH_DETAIL_TASKS_PROGRESS: 'Tasks completed {{completed}}/{{total}} ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_MANDAY_USAGE: '{{used}} / {{budget}} Manday ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_NO_BUGS: 'Clean, no open bugs (0/0)',
      PROJECT_HEALTH_DETAIL_BUGS_PROGRESS: 'Fixed {{closed}}/{{total}} bugs ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_NO_PHASES: 'No phases (0/0)',
      PROJECT_HEALTH_DETAIL_PHASES_PROGRESS: '{{completed}}/{{total}} Phases ({{percent}}%)',
      PROJECT_HEALTH_DETAIL_ON_SCHEDULE: 'On Schedule',
      PROJECT_HEALTH_DETAIL_DELAYED: 'Behind Schedule',
      PROJECT_HEALTH_DETAIL_COMPLETED: 'Completed as Planned',
      PROJECT_HEALTH_DETAIL_OVERDUE: 'Overdue / Delivery Passed',
      PORTFOLIO_GANTT_TITLE: 'Enterprise Portfolio Roadmap (Gantt Chart)',
      PORTFOLIO_GANTT_SUBTITLE: 'Project timeline and execution status across all enterprise customers',
      PORTFOLIO_GANTT_TOTAL_CUSTOMERS: 'Total Customers',
      PORTFOLIO_GANTT_TOTAL_PROJECTS: 'Total Projects',
      PORTFOLIO_GANTT_ACTIVE: 'Active',
      PORTFOLIO_GANTT_DELAYED: 'Delayed',
      PORTFOLIO_GANTT_COMPLETED: 'Completed',
      PORTFOLIO_GANTT_EXPAND_ALL: 'Expand All',
      PORTFOLIO_GANTT_COLLAPSE_ALL: 'Collapse All',
      PORTFOLIO_GANTT_VIEW_MONTH: 'Month',
      PORTFOLIO_GANTT_VIEW_WEEK: 'Week',
      PORTFOLIO_GANTT_VIEW_DAY: 'Day',
      PORTFOLIO_GANTT_SEARCH_PLACEHOLDER: 'Search project, customer, or PM...',
      PORTFOLIO_GANTT_CUSTOMER_ALL: 'All Customers',
      PORTFOLIO_GANTT_STATUS_ALL: 'All Statuses',
      PORTFOLIO_GANTT_LEGEND_ON_TRACK: 'On Track',
      PORTFOLIO_GANTT_LEGEND_DELAYED: 'Behind Schedule',
      PORTFOLIO_GANTT_LEGEND_PLANNING: 'Planning',
      PORTFOLIO_GANTT_LEGEND_COMPLETED: 'Completed',
      PORTFOLIO_GANTT_NO_DATA: 'No project data found for current filters',
      PORTFOLIO_GANTT_VIEW_DETAILS: 'View Project Details',
      PORTFOLIO_GANTT_VIEW_BOARD: 'Open Task Board & Phase Gantt',
      PORTFOLIO_GANTT_PROJECTS_COUNT: '{{count}} projects',
      PMDT17A_CONTRACT_LABEL: 'Contract',
      PMDT17A_SELECT_CONTRACT_PLACEHOLDER: 'Select contract',
      PMDT16A_LBL_DELIVERY: 'Delivery',
      PMDT16A_PH_DELIVERY: 'Select delivery',
      PMDT14_GATE_CHECK_TITLE: 'Delivery Gate Check',
      PMDT14_CHECK_GATE_BTN: 'Re-check',
      PMDT14_CHECKING: 'Checking...',
      PMDT14_PASSED_MARK: 'Passed',
      PMDT14_FAILED_MARK: 'Action Required',
      PMDT14_VIEW_DATA: 'View Details',
      PMDT14_GO_MANAGE_PENDING: 'Manage Pending',
      PMDT14_GATE_STATUS_LABEL: 'Gate Check Status:',
      PMDT14_STATUS_READY: 'Ready to Deliver',
      PMDT14_HAS_CONDITIONS: 'Conditions Pending',
      PMDT14_PASSED_WORD: 'Passed',
      PMDT14_OUT_OF_WORD: 'out of',
      PMDT14_CHECKS_WORD: 'checks',
      PMDT14_GATE_EMPTY_HINT: 'Please select a contract or project to run delivery gate check',
      PMDT14_CLICK_TO_MANAGE_TIP: 'Click to manage items in this module',
      PMDT10_PAGE_DESC: 'Track real-time task progress and traceability',
      PMDT10_TOTAL_LABEL: 'Total',
      PMDT10_UNIT_TASK: 'Tasks',
      PMDT10_INPROGRESS_LABEL: 'In Progress',
      PMDT10_BUG_LABEL: 'Open Bugs',
      PMDT10_BUG_DONE_LABEL: 'Resolved Bugs',
      PMDT10_DONE_LABEL: 'Completed',
      PMDT10_CREATE_TASK_BTN: 'Create Task',
      PMDT10_NO_TASK_TITLE: 'No Tasks Yet',
      PMDT10_NO_TASK_DESC: 'Get started by creating a new task to track work progress',
      PMDT10_SELECT_PROJECT_MSG: 'No Tasks Yet',
      PMDT10_SELECT_PROJECT_HINT: 'Get started by creating a new task to track work progress',
      PMDT10_GO_PROJECT_LIST_BTN: 'Create Task',
      PMDT10_SEARCH_PH: 'Search task name, code...',
      PMDT10_SPEC_PH: 'All Specifications',
      PMDT10_WP_PH: 'All Work Packages',
      PMDT10_PRIORITY_PH: 'All Priorities',
      PMDT10_ASSIGNEE_PH: 'All Assignees',
      PMDT10_CLEAR_FILTER_BTN: 'Clear Filters',
      PMDT10_TABLE_VIEW_BTN: 'Table',
      PMDT10_LOADING_TASK: 'Loading tasks...',
      PMDT10_DELETE_TASK_TITLE: 'Delete Task',
      PMDT10_PRIO_CRITICAL: 'Critical',
      PMDT10_PRIO_HIGH: 'High',
      PMDT10_PRIO_MEDIUM: 'Medium',
      PMDT10_PRIO_LOW: 'Low',
      PMDT10_PRIO_CRITICAL_PLAIN: 'Critical',
      PMDT10_PRIO_HIGH_PLAIN: 'High',
      PMDT10_PRIO_MEDIUM_PLAIN: 'Medium',
      PMDT10_PRIO_LOW_PLAIN: 'Low',
      PMDT10_COL_TASK_CODE: 'Task Code',
      PMDT10_COL_TASK_NAME: 'Task Name',
      PMDT10_COL_ASSIGNEE: 'Assignee',
      PMDT10_COL_MANDAY: 'Manday (Actual / Est)',
      PMDT10_COL_STATUS: 'Status',
      PMDT10_COL_PRIORITY: 'Priority',
      PMDT10_COL_DUE_DATE: 'Due Date',
      PMDT10_COL_ACTIONS: 'Actions',
      PMDT10_EDIT_TASK_TITLE: 'Edit Task',
      PMDT10_NEW_TASK_TITLE: 'Create Task',
      PMDT10_MODAL_DESC: 'Fill in task details and assignees',
      PMDT10_SPEC_TRACE_LABEL: 'Specification (Traceability)',
      PMDT10_SPEC_SELECT_PH: 'Select Specification...',
      PMDT10_SPEC_REQUIRED_MSG: 'Please select a Specification',
      PMDT10_WP_LABEL: 'Work Package',
      PMDT10_WP_SELECT_PH: 'Select Work Package...',
      PMDT10_WP_REQUIRED_MSG: 'Please select a Work Package',
      PMDT10_TASK_CODE_LABEL: 'Task Code',
      PMDT10_TASK_CODE_PH: 'e.g. TSK-001',
      PMDT10_TASK_CODE_REQUIRED_MSG: 'Task code is required',
      PMDT10_TASK_NAME_LABEL: 'Task Name',
      PMDT10_TASK_NAME_PH: 'e.g. Develop User Interface',
      PMDT10_TASK_NAME_REQUIRED_MSG: 'Task name is required',
      PMDT10_TASK_DESC_LABEL: 'Description',
      PMDT10_TASK_DESC_PH: 'Describe task details...',
      PMDT10_ASSIGNEE_FIELD_LABEL: 'Assignee',
      PMDT10_ASSIGNEE_FIELD_PH: 'Select assignee...',
      PMDT10_START_DATE_LABEL: 'Start Date',
      PMDT10_START_DATE_PH: 'Select start date',
      PMDT10_START_TIME_LABEL: 'Start Time',
      PMDT10_END_DATE_LABEL: 'End Date',
      PMDT10_END_DATE_PH: 'Select end date',
      PMDT10_END_TIME_LABEL: 'End Time',
      PMDT10_TIME_PH: '09:00',
      PMDT10_ESTIMATE_MANDAY_LABEL: 'Estimate Manday',
      PMDT10_ACTUAL_MANDAY_LABEL: 'Actual Manday',
      PMDT10_PRIORITY_FIELD_LABEL: 'Priority',
      PMDT10_PRIORITY_SELECT_PH: 'Select priority',
      PMDT10_COLOR_TAG_LABEL: 'Color Tag',
      PMDT10_CANCEL_BTN: 'Cancel',
      PMDT10_SAVING_TEXT: 'Saving...',
      PMDT10_SAVE_EDIT_BTN: 'Save Changes',
      PMDT10_CONFIRM_DELETE_TITLE: 'Confirm Delete',
      PMDT10_CONFIRM_DELETE_MSG: 'Are you sure you want to delete this task?',
      PMDT10_DELETE_SUCCESS_TITLE: 'Deleted',
      PMDT10_DELETE_SUCCESS_MSG: 'Task has been deleted successfully',
      PMDT10_DELETE_ERROR_TITLE: 'Error',
      PMDT10_INCOMPLETE_DATA_TITLE: 'Incomplete Data',
      PMDT10_INCOMPLETE_DATA_MSG: 'Please fill in all required fields (*)',
      PMDT10_SAVE_SUCCESS_TITLE_A: 'Saved',
      PMDT10_CREATE_TASK_SUCCESS_MSG: 'Task created successfully',
      PMDT10_UPDATE_TASK_SUCCESS_MSG: 'Task updated successfully',
      PMDT10_SAVE_ERROR_TITLE_A: 'Save Failed',
      PMDT10_SAVE_TASK_ERROR_MSG: 'An error occurred while saving task',
      PMDT10_LOAD_FAIL_TITLE: 'Load Failed',
      PMDT10_LOAD_TASKS_FAIL_MSG: 'Could not load tasks',
      PMDT10_LOAD_BUGS_FAIL_MSG: 'Could not load bugs',
      PMDT10_NO_FILTER_RESULT_MSG: 'No tasks match your search criteria',
      PMDT09_PROJECT_LABEL: 'Project',
      PMDT09_PROJECT_PLACEHOLDER: 'Select project',
      PMDT09_REVIEW_CODE_LABEL: 'Review Code',
      PMDT09_REVIEW_CODE_PLACEHOLDER: 'e.g. DR-001',
      PMDT09_TITLE_LABEL: 'Review Title',
      PMDT09_TITLE_PLACEHOLDER: 'Enter review title',
      PMDT09_SEVERITY_FIELD_LABEL: 'Severity',
      PMDT09_SEV_SELECT_PH: 'Select severity',
      PMDT09_STATUS_LABEL: 'Status',
      PMDT09_STATUS_SELECT_PH: 'Select status',
      PMDT09_DUE_DATE_LABEL: 'Resolution Due Date',
      PMDT09_ASSIGNED_TO_LABEL: 'Assigned Fixer',
      PMDT09_ASSIGNED_TO_PH: 'Select assignee...',
      PMDT09_APPROVAL_FLOW_LABEL: 'Approval Flow',
      PMDT09_APPROVAL_FLOW_PH: 'Select approval flow...',
      PMDT09_DESC_LABEL: 'Description',
      PMDT09_DESC_PLACEHOLDER: 'Enter review details, comments or improvements...',
      PMDT09_FIGMA_URL_LABEL: 'Figma File / Prototype URL',
      PMDT09_FIGMA_URL_PH: 'https://www.figma.com/file/...',
      PMDT09_PAGE_TITLE: 'Design Review',
      PMDT09_PAGE_DESC: 'Review and approve UI/UX designs from Figma and prototypes',
      PMDT09_CREATE_BTN: 'Create Design Review',
      PMDT09_SEARCH_PLACEHOLDER: 'Search code, title, creator...',
      PMDT09_STATUS_PLACEHOLDER: 'All Statuses',
      PMDT09_TYPE_PLACEHOLDER: 'All Types',
      PMDT09_SEVERITY_PLACEHOLDER: 'All Severities',
      PMDT09_EMPTY_TITLE: 'No Design Reviews Found',
      PMDT09_EMPTY_DESC: 'Get started by creating a new design review to inspect screens and flows',
      PMDT09_CANCEL_BTN: 'Cancel',
      PMDT09_SAVE_BTN: 'Save',
      PMDT09_SUBMIT_APPROVAL_BTN: 'Submit for Approval',
      PMDT03_PAGE_TITLE: 'Approval Center',
      PMDT03_SUBTITLE: 'Manage approval workflows and pending requests',
      PMDT03_MY_PENDING_TITLE: 'Pending My Approval',
      PMDT03_OVERDUE_TITLE: 'Overdue Approvals',
      PMDT03_ALL_STATUS_PLACEHOLDER: 'All Statuses',
      PMDT03_SELECT_PROJECT_PLACEHOLDER: 'Select Project',
      PMDT03_COL_TYPE_CODE: 'Document Type / Code',
      PMDT03_COL_ITEM: 'Title / Subject',
      PMDT03_COL_PROJECT: 'Project',
      PMDT03_COL_REQUESTER: 'Requester',
      PMDT03_COL_REQUESTED_DATE: 'Requested Date',
      PMDT03_COL_STATUS: 'Status',
      PMDT03_COL_ACTIONS: 'Actions',
      PMDT03_STATUS_PENDING: 'Pending',
      PMDT03_STATUS_APPROVED: 'Approved',
      PMDT03_STATUS_REJECTED: 'Rejected',
      PMDT03_STATUS_NEED_REVISION_OPT: 'Need Revision',
      PMDT03_STATUS_CANCELLED: 'Cancelled',
      PMDT03_PROJECT_CRM: 'Customer Relationship Management (CRM)',
      PMDT03_PROJECT_HR: 'Human Resource Management (HRMS)',
      PMDT03_ITEMS_SUFFIX: 'items',
      PMDT03_ITEMS_UNIT: 'items',
      PMDT03_NO_USER_TITLE: 'User Info Not Found',
      PMDT03_RELOGIN_MSG: 'Please sign in again',
      PMDT07_REQUIREMENT_LABEL: 'Requirement',
      PMDT07_REQUIREMENT_PLACEHOLDER: 'Select Requirement',
      PMDT07_SPEC_CODE_LABEL: 'Specification Code',
      PMDT07_SPEC_CODE_PLACEHOLDER: 'e.g. SPEC-001',
      PMDT07_SPEC_TYPE_LABEL: 'Specification Type',
      PMDT07_SPEC_TYPE_PLACEHOLDER: 'Select Specification Type',
      PMDT07_TITLE_LABEL: 'Specification Title',
      PMDT07_TITLE_PLACEHOLDER: 'Enter title',
      PMDT07_PRIORITY_LABEL: 'Priority',
      PMDT07_PRIORITY_PLACEHOLDER: 'Select Priority',
      PMDT07_ASSIGNEE_LABEL: 'Assignee',
      PMDT07_ASSIGNEE_PLACEHOLDER: 'Select Assignee',
      PMDT07_ESTIMATED_MANDAY_LABEL: 'Estimated Manday',
      PMDT07_ESTIMATED_MANDAY_PLACEHOLDER: 'Enter manday',
      PMDT07_DESC_LABEL: 'Specification Description',
      PMDT07_DESC_PLACEHOLDER: 'Type description here...',
      PMDT07_ATTACHMENTS_LABEL: 'Attachments',
      PMDT07_ATTACHMENTS_HELPER: 'Drag & drop files here, or click to browse',
      PMDT07_CREATE_SPEC_TITLE: 'Create Specification',
      PMDT07_EDIT_SPEC_TITLE: 'Edit Specification',
      PMDT07_VIEW_SPEC_TITLE: 'Specification Details',
      PMDT07_CANCEL_BTN: 'Cancel',
      PMDT07_SAVE_BTN: 'Save',
      PMDT07_SUBMIT_BTN: 'Submit for Approval',
      PMDT07_HEADER_TITLE: 'Specification',
      PMDT01_CREATE_PHASE_TITLE: 'Create Phase',
      PMDT01_EDIT_PHASE_TITLE: 'Edit Phase',
      PMDT01_EMPTY_TITLE: 'No Phases in this Project',
      PMDT01_EMPTY_HINT: 'Get started by clicking "+ Add Phase" above to plan project phases and milestones.',
      PMDT01_CUSTOMER_LABEL: 'Customer',
      PMDT01_CUSTOMER_PLACEHOLDER: 'Search and select customer',
      PMDT01_PROJECT_LABEL: 'Project',
      PMDT01_PROJECT_PLACEHOLDER: 'Search and select project',
      PMDT02_CREATE_MS_TITLE_H: 'Create Milestone',
      PMDT02_EDIT_MS_TITLE_H: 'Edit Milestone',
      PMDT02_PHASE_LABEL: 'Phase',
      PMDT02_SELECT_PHASE_PLACEHOLDER: 'Search and select phase',
      PMDT02_CREATE_WP_TITLE_H: 'Create Work Package',
      PMDT02_EDIT_WP_TITLE_H: 'Edit Work Package',
      PMDT02_MILESTONE_LABEL: 'Milestone',
      PMDT02_SELECT_MILESTONE_PLACEHOLDER: 'Search and select milestone',
      PMDT02_CREATE_TASK_TITLE_H: 'Create Task',
      PMDT02_EDIT_TASK_TITLE_H: 'Edit Task',
      PMDT02_WORK_PACKAGE_LABEL: 'Work Package',
      PMDT02_SELECT_WP_PLACEHOLDER: 'Search and select work package',
      PMDT06_CUSTOMER_LABEL: 'Customer',
      PMDT06_CUSTOMER_PLACEHOLDER: 'Search and select customer',
      PMDT06_PROJECT_LABEL: 'Project',
      PMDT06_PROJECT_PLACEHOLDER: 'Search and select project',
      PMDT06_UPSTREAM_CONTEXT_LABEL: 'Impacted Projects & Customers (Upstream)',
      PMDT06_IMPACT_CUSTOMERS_LABEL: 'Impacted Customers',
      PMDT06_IMPACT_PROJECTS_LABEL: 'Impacted Projects',
      PMDT06_IMPACT_REQUIREMENT: 'Requirements',
      PMDT06_IMPACT_SPECIFICATION: 'Specifications',
      PMDT06_IMPACT_DIAGRAM: 'Diagrams',
      PMDT06_IMPACT_TASK: 'Tasks',
      PMDT06_IMPACT_TESTCASE: 'Test Cases',
      PMDT06_IMPACT_TESTPLAN: 'Test Plans',
      PMDT06_IMPACT_BUG: 'Bugs',
      PMDT06_IMPACT_CONTRACT: 'Contracts',
      PMDT06_IMPACT_DESIGNREVIEW: 'Design Reviews',
      PMDT06_IMPACT_DELIVERY: 'Deliveries',
      PMDT06_IMPACT_USERMANUAL: 'User Manuals',
      PMDT06_IMPACT_INVOICE: 'Invoices & Payments',
      PMDT06_IMPACT_MATICKET: 'MA Tickets',
      PMDT06_IMPACT_MARENEWAL: 'MA Renewals',
      PMDT12_SEARCH_PLACEHOLDER: 'Search scenario, case code, title, tester...',
      PMDT12_FILTER_STATUS_PH: '📊 All Test Case Statuses',
      PMDT12_FILTER_PRIORITY_PH: '⚡ All Priorities',
      PMDT12_FILTER_TASK_STATUS_PH: '🎯 All Task Statuses',
      PMDT12_SEVERITY_LABEL: 'Severity',
      PMDT12_SEVERITY_PH: 'Select severity',
      PMDT12_BUG_TITLE_LABEL: 'Bug Title / Summary',
      PMDT12_BUG_TITLE_PH: 'Enter bug details...',
      PMDT12_ASSIGNED_TO_LABEL: 'Assigned Fixer',
      PMDT12_ASSIGNED_TO_PH: 'Select assignee',
      PMDT12_MANDAY_LABEL: 'Estimated Manday',
      PMDT12B_TASK_TRACE_LABEL: 'Task',
      PMDT12B_TASK_TRACE_PLACEHOLDER: 'Select Task',
      PMDT12B_SCENARIO_CODE_LABEL: 'Test Scenario Code',
      PMDT12B_SCENARIO_CODE_PLACEHOLDER: 'e.g. SC-001, SC-LOGIN',
      PMDT12B_SCENARIO_NAME_LABEL: 'Test Scenario Name',
      PMDT12B_SCENARIO_NAME_PLACEHOLDER: 'e.g. Login, Report printing...',
      PMDT12B_TEST_TYPE_LABEL: 'Test Type',
      PMDT12B_TEST_TYPE_PLACEHOLDER: 'Select test type',
      PMDT12B_PRIORITY_LABEL: 'Priority',
      PMDT12B_PRIORITY_PLACEHOLDER: 'Select priority level',
      PMDT12B_DESCRIPTION_LABEL: 'Description / Scenario Purpose',
      PMDT12B_DESCRIPTION_PLACEHOLDER: 'Describe the scope and objective of testing for this group...',
      PMDT12B_RICH_TEXT_HINT: 'Rich text formatting supported',
      PMDT12B_STATUS_ACTIVE_LABEL: 'Active',
      PMDT14_CANCEL_BTN: 'Cancel',
      AIWIZARD_HEADING: 'AI Full-Project Generator',
      AIWIZARD_SUBHEADING: 'Build a complete project structure with fully linked modules using AI in a single click',
      AIWIZARD_HISTORY_TITLE: 'AI Project Creation History',
      AIWIZARD_HISTORY_EMPTY: 'No project creation history yet',
      AIWIZARD_HISTORY_LOADING: 'Loading history...',
      AIWIZARD_FAILED_MODULES_TITLE: 'Modules not created',
      AIWIZARD_SKIPPED_STEP_MSG: 'Skipped because a previous step did not succeed',
      AIWIZARD_STEP1_LABEL: '1. Project Brief',
      AIWIZARD_STEP2_LABEL: '2. Review Structure',
      AIWIZARD_STEP3_LABEL: '3. Generate All Data',
      AIWIZARD_STEP4_LABEL: '4. Start Project Review',
      AIWIZARD_PROJECT_NAME_LABEL: 'Project Name (optional)',
      AIWIZARD_BRIEF_LABEL: 'Description / Project Requirements (Brief)',
      AIWIZARD_DURATION_LABEL: 'Estimated Project Duration (weeks)',
      AIWIZARD_MODEL_LABEL: 'AI Engine Model',
      AIWIZARD_TOR_LABEL: 'TOR Document or Reference Attachments',
      AIWIZARD_MODULE_CONTRACT: 'Contract',
      AIWIZARD_MODULE_TEST: 'Test Scenario & Test Case',
      AIWIZARD_MODULE_MANUAL: 'User Manual',
      AIWIZARD_MODULE_INVOICE: 'Draft Invoice from Delivery Milestones',
      AIWIZARD_MODULE_DIAGRAM: 'Diagram (DFD / ER / Flowchart / Use Case)',
      AIWIZARD_MODULE_DESIGN_REVIEW: 'Design Review',
      AIWIZARD_MODULE_MA: 'MA Ticket & MA Renewal Proposal',
      AIWIZARD_SAMPLE_REQUIREMENTS: 'Sample Requirements List',
      AIWIZARD_SAMPLE_SPECIFICATIONS: 'Sample Specifications List',
      AIWIZARD_GENERATING_TITLE: 'AI is creating the project and modules in SDLC order...',
      AIWIZARD_GENERATING_DESC: 'Running in the background, takes about 2-5 minutes, please wait until it finishes',
      AIWIZARD_SUCCESS_TITLE: 'Project created successfully!',
      AIWIZARD_DRAFT_BADGE: 'Draft (Pending Review)',
      AIWIZARD_STARTING: 'Starting...',
      AIWIZARD_CREATING_LABEL: 'Creating: {{label}}',
      AIWIZARD_PROGRESS_DONE: 'Done {{done}}/{{total}} steps',
      AIWIZARD_PROGRESS_FAILED_SUFFIX: ' (failed {{failed}})',
      AIWIZARD_COUNT_PROJECT: 'Project',
      AIWIZARD_COUNT_CONTRACT: 'Contract',
      AIWIZARD_COUNT_WBS: 'Phase / Milestone / WP',
      AIWIZARD_COUNT_REQUIREMENT: 'Requirements',
      AIWIZARD_COUNT_SPECIFICATION: 'Specifications',
      AIWIZARD_COUNT_TASK: 'Tasks',
      AIWIZARD_COUNT_TEST: 'Test Scenario / Case',
      AIWIZARD_COUNT_DELIVERY: 'Deliveries',
      AIWIZARD_COUNT_MANUAL: 'User Manual',
      AIWIZARD_COUNT_INVOICE: 'Draft Invoice',
      AIWIZARD_COUNT_DIAGRAM: 'Diagrams',
      AIWIZARD_COUNT_DESIGN_REVIEW: 'Design Review',
      AIWIZARD_COUNT_MA: 'MA Ticket / Renewal',
      AIWIZARD_STATUS_RUNNING: 'Running',
      AIWIZARD_STATUS_COMPLETED: 'Completed',
      AIWIZARD_STATUS_COMPLETED_WITH_ERRORS: 'Partially Completed',
      AIWIZARD_STATUS_FAILED: 'Failed',
      AIWIZARD_ERROR_TITLE: 'Error',
      AIWIZARD_TRY_AGAIN: 'Please try again',
      AIWIZARD_ANALYZE_ERROR_MSG: 'An error occurred while analyzing the project: {{msg}}',
      AIWIZARD_ATTACHMENT_ERROR_MSG: 'An error occurred while processing the attached files',
      AIWIZARD_START_PIPELINE_ERROR_MSG: 'An error occurred while starting project creation: {{msg}}',
      AIWIZARD_CREATE_PROJECT_FAILED_MSG: 'Failed to create the project',
      AIWIZARD_PARTIAL_SUCCESS_TITLE: 'Partially Completed',
      AIWIZARD_SOME_STEPS_FAILED_MSG: 'Some steps failed',
      AIWIZARD_POLL_ERROR_MSG: 'Unable to track progress (the job may still be running in the background; check the project list again)',
      AIWIZARD_LOAD_HISTORY_ERROR_MSG: 'Unable to load project creation history',
      AIWIZARD_BTN_HISTORY: 'History',
      AIWIZARD_BTN_HISTORY_TITLE: 'Project Creation History',
      AIWIZARD_CLOSE_BTN: 'Close',
      AIWIZARD_NO_PROJECT_NAME: '(No project name)',
      AIWIZARD_PAGE_INFO: 'Page {{page}} / {{total}}',
      AIWIZARD_UNIT_WEEKS: 'weeks',
      AIWIZARD_GO_TO_PROJECT_BTN: 'Go to this Project',
      AIWIZARD_ANALYZING_BANNER: 'AI is analyzing the brief and planning project structure, please wait...',
      AIWIZARD_PROJECT_NAME_PLACEHOLDER: 'e.g., Smart Warehouse and Delivery Management System',
      AIWIZARD_BRIEF_PLACEHOLDER: 'Describe required features, target users, business goals, or project scope for AI structuring...',
      AIWIZARD_CUSTOMER_LABEL: 'Customer',
      AIWIZARD_CUSTOMER_HINT: 'Select from system or leave blank for AI auto-match/create',
      AIWIZARD_CUSTOMER_AUTO_OPTION: '-- Automatic (AI Smart Match / Auto-create) --',
      AIWIZARD_ATTACH_TOR_BTN: 'Attach TOR / Brief files',
      AIWIZARD_ESTIMATED_DURATION: 'Project Duration: {{weeks}} weeks',
      AIWIZARD_SELECT_MODULES_LABEL: 'Select modules for AI to generate automatically:',
      AIWIZARD_MODULE_REQUIREMENTS_COUNT: 'Requirements ({{count}} items)',
      AIWIZARD_MODULE_SPECS_COUNT: 'System Specifications ({{count}} items)',
      AIWIZARD_MODULE_TASKS_COUNT: 'WBS / Tasks Breakdown ({{count}} items)',
      AIWIZARD_MODULE_GANTT_COUNT: 'Gantt Phases & Timeline ({{count}} phases)',
      AIWIZARD_MODULE_DELIVERY_COUNT: 'Delivery Milestones ({{count}} milestones)',
      AIWIZARD_SUCCESS_DESC_PREFIX: 'All data has been saved in',
      AIWIZARD_SUCCESS_DESC_SUFFIX: 'status with complete Traceability across all modules',
      AIWIZARD_CANCEL_BTN: 'Cancel',
      AIWIZARD_ANALYZING_BTN: 'AI is analyzing brief...',
      AIWIZARD_PREVIEW_BTN: 'Analyze & Preview Plan',
      AIWIZARD_ADJUST_BRIEF_BTN: 'Adjust Brief',
      AIWIZARD_CONFIRM_CREATE_BTN: 'Confirm & Generate Entire Project',
      AIWIZARD_VIEW_GANTT_BTN: 'View in Gantt Chart',
      AIWIZARD_REVIEW_PROJECT_BTN: 'Review This Project',
      AIWIZARD_STEP_CUSTOMER: 'Customer',
      AIWIZARD_STEP_PROJECT: 'Create Project',
      AIWIZARD_STEP_CONTRACT: 'Contract',
      AIWIZARD_STEP_WBS: 'Phase / Milestone / Work Package',
      AIWIZARD_STEP_REQUIREMENT: 'Requirement',
      AIWIZARD_STEP_DIAGRAM: 'Diagram (DFD / ER / Flowchart / Use Case)',
      AIWIZARD_STEP_SPECIFICATION: 'Specification',
      AIWIZARD_STEP_DESIGN_REVIEW: 'Design Review',
      AIWIZARD_STEP_TASK: 'Task',
      AIWIZARD_STEP_TEST: 'Test Scenario / Test Case',
      AIWIZARD_STEP_DELIVERY: 'Delivery Milestones',
      AIWIZARD_STEP_MANUAL: 'User Manual',
      AIWIZARD_STEP_INVOICE: 'Draft Invoice',
      AIWIZARD_STEP_MA: 'MA Ticket / Renewal',

      BURT03_ADD_NODE_TITLE: 'Add Role',
      BURT03_EDIT_NODE_TITLE: 'Edit Role',
      BURT03_ROLE_CODE: 'Role Code',
      BURT03_NAME_EN: 'Role Name (EN)',
      BURT03_NAME_LOCAL: 'Role Name (Local)',
      BURT03_COLOR: 'Badge Color',
      BURT03_EDIT_ROLE: 'Edit Role',
      BURT03_ADD_SUB_ROLE: 'Add Sub-role',
      BURT03_REMOVE_ROLE: 'Remove Role',
      COMMON_SAVE_BTN: 'Save',

      PMDT05_ACTIVE_BADGE: 'Active',
      PMDT05_AI_ASSISTANT_TITLE: 'AI Diagram Assistant',
      PMDT05_AI_CONNECT_ERROR_MSG: 'Unable to connect to AI at this moment. Please try again.',
      PMDT05_AI_DIAGRAM_ASSISTANT: 'AI Diagram Assistant',
      PMDT05_AI_MODEL_LABEL: 'AI Model',
      PMDT05_AI_MODEL_PLACEHOLDER: 'Select AI model',
      PMDT05_AI_PROCESSING_LABEL: 'AI is processing...',
      PMDT05_AI_WELCOME_DESC: 'Intelligent assistant for generating and refining DFD, ER, Flowchart diagrams and analyzing system architecture',
      PMDT05_ALL_PROJECTS: 'All Projects',
      PMDT05_APPROVAL_PROCESS_LABEL: 'Approval Workflow',
      PMDT05_APPROVED_BADGE: 'Approved',
      PMDT05_APPROVED_LABEL: 'Approved',
      PMDT05_APPROVED_TITLE: 'Document Approved',
      PMDT05_AUTO_MIGRATION_MODE: 'Generate Migration Script v{0}',
      PMDT05_AUTO_SAVED: 'Auto-saved',
      PMDT05_BACK_LABEL: 'Back',
      PMDT05_BACK_TO_CHAT_TITLE: 'Back to chat',
      PMDT05_BY_PREFIX: 'By: ',
      PMDT05_CANCEL_BTN: 'Cancel',
      PMDT05_CHAT_BTN: 'AI Assistant',
      PMDT05_CHAT_HISTORY_LABEL: 'Chat History',
      PMDT05_CHAT_INPUT_PLACEHOLDER: 'Type instructions or ask AI for advice...',
      PMDT05_CHAT_TITLE: 'AI Assistant',
      PMDT05_CLEAR_CHAT_TITLE: 'Clear Chat',
      PMDT05_CLOSE_BTN: 'Close',
      PMDT05_CLOSE_CHAT_TITLE: 'Close Chat',
      PMDT05_CONNECTING: 'Connecting...',
      PMDT05_COPIED_LABEL: 'Copied',
      PMDT05_COPIED_TEXT: 'Copied',
      PMDT05_COPY_MERMAID_LABEL: 'Copy Mermaid',
      PMDT05_COPY_MERMAID_TITLE: 'Copy Mermaid Code',
      PMDT05_COPY_TEXT: 'Copy',
      PMDT05_CREATE_DIAGRAM_TITLE: 'Create New Diagram',
      PMDT05_CREATE_DIALOG_BTN: 'Create Diagram',
      PMDT05_CREATE_FAIL_TITLE: 'Failed to Create Diagram',
      PMDT05_CREATE_NEW_CHAT_LABEL: 'New Chat',
      PMDT05_CREATE_SUCCESS_MSG: 'Diagram {0} created successfully.',
      PMDT05_CREATE_SUCCESS_TITLE: 'Diagram Created Successfully',
      PMDT05_DB_VENDOR_LABEL: 'Database Vendor',
      PMDT05_DEFAULT_SESSION_TITLE: 'General Conversation',
      PMDT05_DELETE_SESSION_TITLE: 'Delete Chat Session',
      PMDT05_DELETE_TAB_CONFIRM_MSG: 'Are you sure you want to delete diagram \'{0}\'? This action cannot be undone.',
      PMDT05_DELETE_TAB_CONFIRM_TITLE: 'Confirm Delete Diagram',
      PMDT05_DELETE_TAB_FAIL_MSG: 'An error occurred while deleting diagram.',
      PMDT05_DELETE_TAB_TITLE: 'Delete Diagram Tab',
      PMDT05_DELETED_TITLE: 'Deleted Successfully',
      PMDT05_DIAGRAM_CODE_LABEL: 'Diagram Code',
      PMDT05_DIAGRAM_CODE_PLACEHOLDER: 'e.g. DIAG-001 (leave blank for auto-generate)',
      PMDT05_DIAGRAM_COUNT: 'diagrams',
      PMDT05_DIAGRAM_NAME_LABEL: 'Diagram Name',
      PMDT05_DIAGRAM_NAME_PLACEHOLDER: 'Enter diagram name e.g. Order Processing Flow',
      PMDT05_DIAGRAM_TYPE_LABEL: 'Diagram Type',
      PMDT05_DIAGRAM_TYPE_PLACEHOLDER: 'Select diagram type',
      PMDT05_DOWNLOAD_BTN: 'Download',
      PMDT05_DOWNLOAD_SQL_BTN: 'Download SQL File',
      PMDT05_DRAFT_BADGE: 'Draft',
      PMDT05_DRAFT_TITLE: 'Draft',
      PMDT05_DRAW_ER_FIRST_MSG: 'Please draw an ER diagram before generating SQL.',
      PMDT05_DRAWIO_READY: 'Ready',
      PMDT05_EDIT_DIAGRAM_TITLE: 'Edit Diagram Info',
      PMDT05_EDIT_NAME_TITLE: 'Rename or Edit Info',
      PMDT05_EDIT_SESSION_TITLE: 'Edit Session Name',
      PMDT05_EDIT_TAB_TITLE: 'Edit Diagram',
      PMDT05_EMPTY_DIAGRAM_MSG: 'No diagram content found.',
      PMDT05_EMPTY_DIAGRAM_TITLE: 'Empty Diagram',
      PMDT05_ERROR_GENERIC_TITLE: 'Error Occurred',
      PMDT05_ERROR_TITLE: 'Error',
      PMDT05_FAILED_TITLE: 'Operation Failed',
      PMDT05_GEN_FAILED_TITLE: 'Failed to Generate SQL',
      PMDT05_GEN_SQL_FAIL_MSG: 'An error occurred while generating SQL script.',
      PMDT05_GENERATE_SQL_BTN: 'Generate SQL',
      PMDT05_GENERATE_SQL_TITLE: 'Generate SQL script from ER Diagram',
      PMDT05_GENERATED_SQL_RESULT: 'Generated SQL Output',
      PMDT05_GENERATING_TEXT: 'Generating...',
      PMDT05_GEN_MODE_LABEL: 'SQL Generation Mode',
      PMDT05_FULL_REGEN_MODE: 'Generate Full Schema (CREATE TABLE)',
      PMDT05_FULL_REGEN_DESC: 'Generate complete CREATE TABLE scripts and constraints all at once (for fresh setup)',
      PMDT05_FULL_REGEN_BADGE: 'Generate all from scratch',
      PMDT05_GENERIC_ERROR: 'A system error occurred.',
      PMDT05_GET_XML_FAIL_MSG: 'Unable to retrieve XML data from canvas.',
      PMDT05_HIDE_SQL_SCRIPT: 'Hide SQL Script',
      PMDT05_HISTORY_LABEL: 'History',
      PMDT05_HISTORY_LOG_TAB: 'History Log',
      PMDT05_INITIAL_SETUP_DESC: 'Create all new tables along with Foreign Keys and Indexes',
      PMDT05_INITIAL_SETUP_MODE: 'Initial Database Setup',
      PMDT05_INSERT_MERMAID_FAIL_MSG: 'Unable to insert diagram onto canvas.',
      PMDT05_INSERT_MERMAID_FAIL_TITLE: 'Failed to Insert Diagram',
      PMDT05_INSERT_MERMAID_LABEL: 'Insert into Diagram',
      PMDT05_INSERT_MERMAID_SUCCESS_MSG: 'Diagram inserted into canvas successfully.',
      PMDT05_INSERT_MERMAID_SUCCESS_TITLE: 'Diagram Inserted Successfully',
      PMDT05_INSERT_MERMAID_TITLE: 'Insert Mermaid code into Draw.io canvas',
      PMDT05_LOAD_FAIL_TITLE: 'Failed to Load Diagram',
      PMDT05_LOADING_DIAGRAM: 'Loading diagram...',
      PMDT05_LOADING_HISTORY_LOG: 'Loading generation history...',
      PMDT05_LOADING_TABS: 'Loading tabs...',
      PMDT05_LOCKED_DELETE_MSG: 'This diagram is approved and cannot be deleted.',
      PMDT05_LOCKED_MSG: 'This diagram is approved and cannot be edited.',
      PMDT05_LOCKED_SAVE_MSG: 'Cannot save because the document has been approved.',
      PMDT05_LOCKED_TITLE: 'Document Locked',
      PMDT05_MESSAGES_COUNT_SUFFIX: 'messages',
      PMDT05_MIGRATION_BASED_ON: 'Compare differences against version {0}',
      PMDT05_MIGRATION_MODE_DESC: 'Generate ALTER TABLE / ADD COLUMN statements to update database without losing data',
      PMDT05_MISSING_REQ_MSG: 'Please fill in all required fields.',
      PMDT05_MISSING_REQ_TITLE: 'Incomplete Information',
      PMDT05_NEEDS_REVISION_BADGE: 'Needs Revision',
      PMDT05_NEW_CHAT_LABEL: 'New Chat',
      PMDT05_NEW_DIAGRAM_BTN: '+ Create New Diagram',
      PMDT05_NEW_SESSION_TITLE: 'New Chat Session',
      PMDT05_NEW_SESSION_TITLE_DEFAULT: 'New Chat Session',
      PMDT05_NO_CHAT_HISTORY_MSG: 'No chat history yet',
      PMDT05_NO_DIAGRAM_SAVE_MSG: 'Please open or create a diagram before saving.',
      PMDT05_NO_DIAGRAM_TITLE: 'No Diagram Found',
      PMDT05_NO_ER_PAGE_MSG: 'Please select an ER Diagram page before generating SQL.',
      PMDT05_NO_HISTORY_FOUND: 'No matching chat history found',
      PMDT05_NO_HISTORY_MSG: 'No SQL generation history for this diagram yet.',
      PMDT05_NO_MESSAGES_MSG: 'No messages in this chat yet.',
      PMDT05_NO_PAGE_SELECTED_TITLE: 'No Page Selected',
      PMDT05_NO_PROJECT_DESC: 'Please create or select a project before creating diagrams.',
      PMDT05_NO_PROJECT_ID_MSG: 'Project ID not found. Please select a project first.',
      PMDT05_NO_PROJECT_TITLE: 'No Project Selected',
      PMDT05_NO_SEARCH_RESULT: 'No search results found',
      PMDT05_OPEN_DIAGRAM_FIRST_MSG: 'Please open a diagram before proceeding.',
      PMDT05_PAGE_NOT_EXIST_MSG: 'The selected page does not exist.',
      PMDT05_PAGE_NOT_FOUND_TITLE: 'Page Not Found',
      PMDT05_PENDING_BADGE: 'Pending Approval',
      PMDT05_PENDING_TITLE: 'Pending Approval',
      PMDT05_PRESS_ENTER_PREFIX: 'Press ',
      PMDT05_PRESS_ENTER_SUFFIX: ' to send message',
      PMDT05_PREVIEW_SQL_SCRIPT: 'Preview SQL Script',
      PMDT05_PROJECTS_SELECTED: 'projects selected',
      PMDT05_PROMPT_ANALYZE_TEXT: 'Analyze the system architecture and data relationships in this diagram.',
      PMDT05_PROMPT_ANALYZE_TITLE: 'Architecture Analysis',
      PMDT05_PROMPT_ER_TEXT: 'Design an ER Diagram for order and inventory management system.',
      PMDT05_PROMPT_ER_TITLE: 'Design ER Diagram',
      PMDT05_PROMPT_FLOWCHART_TEXT: 'Draw a Flowchart showing checkout and authentication steps.',
      PMDT05_PROMPT_FLOWCHART_TITLE: 'Draw Process Flowchart',
      PMDT05_PROMPT_SEQUENCE_TEXT: 'Draw a Sequence Diagram for API calls from Frontend via Gateway to Backend.',
      PMDT05_PROMPT_SEQUENCE_TITLE: 'Design Sequence Diagram',
      PMDT05_REJECTED_BADGE: 'Rejected',
      PMDT05_REJECTED_TITLE: 'Document Rejected',
      PMDT05_RELOAD_BTN: 'Reload',
      PMDT05_RELOAD_TITLE: 'Reload diagram from server',
      PMDT05_REQ_SOURCE_LABEL: 'Source Requirement',
      PMDT05_REQUEST_CHANGE_BTN: 'Request Change',
      PMDT05_REQUIREMENT_LABEL: 'Link with Requirement (optional)',
      PMDT05_REQUIREMENT_PLACEHOLDER: 'Select Requirement...',
      PMDT05_SAVE_BTN: 'Save',
      PMDT05_SAVE_DIALOG_BTN: 'Save Info',
      PMDT05_SAVE_FAIL_TITLE: 'Save Failed',
      PMDT05_SAVE_FAILED_STATUS: 'Save failed',
      PMDT05_SAVE_LABEL: 'Save',
      PMDT05_SAVE_SUCCESS_MSG: 'Diagram saved successfully.',
      PMDT05_SAVE_SUCCESS_TITLE: 'Saved Successfully',
      PMDT05_SAVE_TITLE: 'Save Diagram',
      PMDT05_SAVE_TITLE_NAME: 'Save Diagram',
      PMDT05_SAVED_MANUALLY: 'Saved manually',
      PMDT05_SAVED_SUFFIX: ' (saved)',
      PMDT05_SAVING_MSG: 'System is saving data. Please wait.',
      PMDT05_SAVING_TITLE: 'Saving...',
      PMDT05_SEARCH_HISTORY_PLACEHOLDER: 'Search chat...',
      PMDT05_SELECT_APPROVAL_FLOW_LABEL: 'Submit to Approval Workflow',
      PMDT05_SELECT_APPROVAL_FLOW_PLACEHOLDER: 'Select approval workflow...',
      PMDT05_SELECT_ER_PAGE_LABEL: 'Select ER Diagram Page',
      PMDT05_SELECT_PAGE_MSG: 'Please select the diagram page to convert to SQL.',
      PMDT05_SEND_BTN: 'Send',
      PMDT05_SQL_GEN_TITLE: 'Generate SQL from ER Diagram',
      PMDT05_START_FIRST_GEN_BTN: 'Start First SQL Generation',
      PMDT05_START_NEW_CHAT_BTN: 'Start New Chat',
      PMDT05_SUBMIT_APPROVAL_COMMENT: 'Submitted diagram for approval from editor',
      PMDT05_SUBMIT_ON_SAVE_HINT: 'When an approval flow is selected, the diagram will be automatically submitted for approval.',
      PMDT05_SUGGESTED_PROMPTS_LABEL: 'Suggested Prompts & Commands:',
      PMDT05_TAB_DELETED_MSG: 'Diagram \'{0}\' deleted successfully.',
      PMDT05_TAB_ID_LABEL: 'Tab ID:',
      PMDT05_UNKNOWN_PROJECT: 'Unknown Project',
      PMDT05_UPDATE_SUCCESS_MSG: 'Diagram \'{0}\' updated successfully.',
      PMDT05_VIEW_ALL_HISTORY_TITLE: 'View All Chat History',

      UPLOAD_DROPZONE_EMPTY_TEXT: 'Drop files here or click to browse',
      UPLOAD_DROPZONE_HELPER_TEXT: 'Multiple files supported',
      UPLOAD_STATUS_QUEUED: 'Queued',
      UPLOAD_STATUS_UPLOADING: 'Uploading',
      UPLOAD_STATUS_PROCESSING: 'Processing',
      UPLOAD_STATUS_PAUSED: 'Paused',
      UPLOAD_STATUS_FAILED: 'Failed',
      UPLOAD_STATUS_STOPPED: 'Stopped',
      UPLOAD_STATUS_COMPLETED: 'Completed',
      UPLOAD_ACTION_PAUSE: 'Pause upload',
      UPLOAD_ACTION_STOP: 'Stop upload',
      UPLOAD_ACTION_RESUME: 'Resume upload',
      UPLOAD_ACTION_DOWNLOAD: 'Download file',
      UPLOAD_ACTION_REMOVE: 'Remove file',

      TRACE_REL_RELATED_TO_TARGET: 'Related to',
      TRACE_REL_RELATED_TO_SOURCE: 'Related to',
      TRACE_REL_DESIGNED_BY_TARGET: 'Designed from',
      TRACE_REL_DESIGNED_BY_SOURCE: 'Designed for',
      TRACE_REL_IMPLEMENTED_BY_TARGET: 'Implemented by',
      TRACE_REL_IMPLEMENTED_BY_SOURCE: 'Implemented for',
      TRACE_REL_DOCUMENTED_BY_TARGET: 'Documented by',
      TRACE_REL_DOCUMENTED_BY_SOURCE: 'Documented for',
      TRACE_REL_VERIFIED_BY_TARGET: 'Verified by',
      TRACE_REL_VERIFIED_BY_SOURCE: 'Verified for',
      TRACE_REL_FAILED_BY_TARGET: 'Failed by',
      TRACE_REL_FAILED_BY_SOURCE: 'Caused failure in',
      TRACE_REL_AFFECTED_BY_TARGET: 'Affected by',
      TRACE_REL_AFFECTED_BY_SOURCE: 'Affects',
    },
  };

  private initPromise: Promise<any> | null = null;

  initLanguage(): Promise<any> {
    if (this.initPromise) {
      return this.initPromise;
    }
    this.translate.setTranslation('th', this.defaultTranslations.th, true);
    this.translate.setTranslation('en', this.defaultTranslations.en, true);
    const lang = this.resolveInitialLanguage();
    this.updateHtmlLang(lang);
    DateTimeUtil.setEra(lang);

    this.initPromise = firstValueFrom(this.translate.use(lang)).catch((err) => {
      console.error('Failed to load translations:', err);
      return null;
    });

    return this.initPromise;
  }

  setLanguage(lang: AppLanguage): void {
    if (isPlatformBrowser(this.platformId)) {
      localStorage.setItem(this.storageKey, lang);
    }

    this.translate.use(lang);
    this.updateHtmlLang(lang);
    DateTimeUtil.setEra(lang);
  }

  getCurrentLanguage(): AppLanguage {
    const current = this.translate.getCurrentLang();
    return (current === 'th' || current === 'en') ? current : 'en';
  }

  private resolveInitialLanguage(): AppLanguage {
    if (isPlatformBrowser(this.platformId)) {
      const saved = localStorage.getItem(this.storageKey);
      if (saved === 'th' || saved === 'en') return saved;
      const browserLang = navigator.language || '';
      return browserLang.toLowerCase().startsWith('th') ? 'th' : 'en';
    }
    return 'en';
  }

  private updateHtmlLang(lang: AppLanguage): void {
    const html = this.document.documentElement;
    html.lang = lang;
    html.dir = 'ltr';
  }
}